from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import pymysql


from PyQt5 import QtCore, QtGui, QtWidgets, uic
import pymysql
import sys
from PyQt5.uic import loadUiType
from PyQt5.QtWidgets import qApp
from PyQt5.QtCore import Qt, QModelIndex
from PyQt5.QtWidgets import QWidget, QApplication, QVBoxLayout, QPushButton, \
    QTableWidget, QTableWidgetItem, QMessageBox, QHBoxLayout, QLineEdit, QLabel, QGridLayout, QHeaderView
from Qualification_add import Ui_Form
from booking_v119 import Ui_BookingDetails


class Ui_Calendar(object):
    def setupUi(self, Calendar):
        Calendar.setObjectName("Calendar")
        Calendar.resize(1035, 685)
        self.centralwidget = QtWidgets.QWidget(Calendar)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 0, 1041, 30))
        self.lineEdit_2.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(870, 440, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(850, 90, 141, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICO/Gnome-Accessories-Text-Editor.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setObjectName("pushButton_12")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(70, 510, 481, 161))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setGeometry(QtCore.QRect(30, 40, 107, 30))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_14.setGeometry(QtCore.QRect(160, 40, 107, 30))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_16.setGeometry(QtCore.QRect(160, 80, 107, 30))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_15.setGeometry(QtCore.QRect(30, 80, 107, 30))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(480, 90, 151, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ICO/Gnome-Dialog-Error.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(720, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("background-color: rgb(171, 171, 171);\n"
"border-color: rgb(0, 0, 0);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(920, 440, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(660, 50, 121, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("myImage.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(780, 50, 121, 30))
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 490, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 50, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(70, 50, 141, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(720, 210, 50, 31))
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(730, 130, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 50, 107, 30))
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(150, 90, 111, 30))
        self.pushButton_6.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ICO/Dialog-Apply.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(360, 90, 121, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ICO/Gnome-Weather-Clear-Night.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 480, 51, 30))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(490, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(630, 90, 91, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ICO/Gnome-Edit-Clear.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon5)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(720, 180, 50, 31))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(260, 90, 107, 30))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ICO/Gnome-Weather-Clear.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(720, 240, 50, 31))
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(720, 150, 50, 31))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(720, 300, 50, 31))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(720, 330, 50, 31))
        self.pushButton_23.setObjectName("pushButton_23")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(640, 490, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(720, 90, 131, 30))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ICO/Gnome-Format-Text-Direction-Ltr.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon7)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 50, 121, 30))
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(600, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("background-color: rgb(188, 255, 169);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(720, 270, 50, 31))
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(760, 490, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(260, 50, 161, 31))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 130, 711, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        Calendar.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Calendar)
        self.statusbar.setObjectName("statusbar")
        Calendar.setStatusBar(self.statusbar)
        self.Show_Calendar()
        self.Show_Calendar_Week()
        self.pushButton_17.clicked.connect(self.openWindow2)

        self.retranslateUi(Calendar)
        QtCore.QMetaObject.connectSlotsByName(Calendar)


    def openWindow2(self):
        self.window2 = QtWidgets.QMainWindow()
        self.ui2 = Ui_BookingDetails()
        self.ui2.setupUi(self.window2)
        self.window2.show()


    def Show_Calendar_Week(self):
        self.db = pymysql.connect(host='129.232.195.18', port=3306, user='pierreb', password='Springboks2017',
                                  db='medx', use_unicode=True,
                                  charset='utf8')
        self.cur = self.db.cursor()

        sql = ''' SELECT WEEKOFYEAR(NOW()) '''
        self.cur.execute(sql)
        data = self.cur.fetchall()
        print(data)


    def Show_Calendar(self):
        self.db = pymysql.connect(host='129.232.195.18', port=3306, user='pierreb', password='Springboks2017',
                                  db='medx', use_unicode=True,
                                  charset='utf8')
        self.cur = self.db.cursor()


        sql = ''' SELECT db_date, day_name Description FROM calendar LIMIT 7 '''
        self.cur.execute(sql)
        data = self.cur.fetchall()


        self.tableWidget.insertRow(0)

        for row, form in enumerate(data):
            for column, item in enumerate(form):
                self.tableWidget.setItem(row, column, QTableWidgetItem(str(item)))
                column += 1

            row_position = self.tableWidget.rowCount()
            self.tableWidget.insertRow(row_position)


    def retranslateUi(self, Calendar):
        _translate = QtCore.QCoreApplication.translate
        Calendar.setWindowTitle(_translate("Calendar", "ProTemp Calendar"))
        self.lineEdit_2.setText(_translate("Calendar", "Booking Calendar"))
        self.pushButton_12.setToolTip(_translate("Calendar", "<html><head/><body><p>Test</p></body></html>"))
        self.pushButton_12.setText(_translate("Calendar", "Bulk Bookings"))
        self.groupBox.setTitle(_translate("Calendar", "Themes"))
        self.pushButton_13.setText(_translate("Calendar", "Theme 1"))
        self.pushButton_14.setText(_translate("Calendar", "Theme 2"))
        self.pushButton_16.setText(_translate("Calendar", "Theme 4"))
        self.pushButton_15.setText(_translate("Calendar", "Theme 3"))
        self.pushButton_9.setToolTip(_translate("Calendar", "<html><head/><body><p>Test</p></body></html>"))
        self.pushButton_9.setText(_translate("Calendar", "Unavailable"))
        self.label_7.setText(_translate("Calendar", "Not Spacified"))
        self.pushButton_4.setToolTip(_translate("Calendar", "<html><head/><body><p>Test</p></body></html>"))
        self.pushButton_4.setText(_translate("Calendar", "Next Week"))
        self.pushButton_5.setToolTip(_translate("Calendar", "<html><head/><body><p>Test</p></body></html>"))
        self.pushButton_5.setText(_translate("Calendar", "This Month"))
        self.label_4.setText(_translate("Calendar", "Booked"))
        self.label_2.setText(_translate("Calendar", "To:"))
        self.pushButton_19.setText(_translate("Calendar", "Book"))
        self.label_12.setText(_translate("Calendar", "Action"))
        self.pushButton_2.setToolTip(_translate("Calendar", "<html><head/><body><p>Test</p></body></html>"))
        self.pushButton_2.setText(_translate("Calendar", "Today"))
        self.pushButton_6.setToolTip(_translate("Calendar", "<html><head/><body><p>Test</p></body></html>"))
        self.pushButton_6.setText(_translate("Calendar", "Any Shift"))
        self.pushButton_8.setToolTip(_translate("Calendar", "<html><head/><body><p>Test</p></body></html>"))
        self.pushButton_8.setText(_translate("Calendar", "Night Only"))
        self.pushButton.setText(_translate("Calendar", "OK"))
        self.label.setText(_translate("Calendar", "From:"))
        self.pushButton_10.setToolTip(_translate("Calendar", "<html><head/><body><p>Test</p></body></html>"))
        self.pushButton_10.setText(_translate("Calendar", "Remove"))
        self.pushButton_18.setText(_translate("Calendar", "Book"))
        self.pushButton_7.setToolTip(_translate("Calendar", "<html><head/><body><p>Test</p></body></html>"))
        self.pushButton_7.setText(_translate("Calendar", "Day Only"))
        self.pushButton_20.setText(_translate("Calendar", "Book"))
        self.label_3.setText(_translate("Calendar", "Set Availability:"))
        self.pushButton_17.setText(_translate("Calendar", "Book"))
        self.pushButton_22.setText(_translate("Calendar", "Book"))
        self.pushButton_23.setText(_translate("Calendar", "Book"))
        self.label_5.setText(_translate("Calendar", "Available"))
        self.pushButton_11.setToolTip(_translate("Calendar", "<html><head/><body><p>Test</p></body></html>"))
        self.pushButton_11.setText(_translate("Calendar", "Bulk Manage"))
        self.pushButton_3.setToolTip(_translate("Calendar", "<html><head/><body><p>Test</p></body></html>"))
        self.pushButton_3.setText(_translate("Calendar", "This Week"))
        self.pushButton_21.setText(_translate("Calendar", "Book"))
        self.label_6.setText(_translate("Calendar", "Unavailable1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Calendar", "Available Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Calendar", "Day"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Calendar", "Availability"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Calendar", "Client"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Calendar", "Department"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Calendar", "Shift"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Calendar", "Type"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calendar = QtWidgets.QMainWindow()
    ui = Ui_Calendar()
    ui.setupUi(Calendar)
    Calendar.show()
    sys.exit(app.exec_())
