from PyQt5 import QtCore, QtWidgets, QtGui
import pymysql

class Ui_CandidateEnrollment(object):
    def setupUi1(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1176, 834)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTabs.setGeometry(QtCore.QRect(10, 10, 1251, 611))
        self.MainTabs.setObjectName("MainTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, -10, 891, 661))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setGeometry(QtCore.QRect(10, 30, 47, 13))
        self.label_1.setObjectName("label_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_1.setGeometry(QtCore.QRect(180, 30, 241, 20))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 60, 241, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 90, 241, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 120, 241, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_12.setGeometry(QtCore.QRect(630, 30, 241, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_19.setGeometry(QtCore.QRect(630, 240, 241, 20))
        self.lineEdit_19.setText("")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(460, 90, 131, 16))
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(460, 210, 131, 16))
        self.label_18.setObjectName("label_18")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_16.setGeometry(QtCore.QRect(630, 150, 241, 20))
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_17.setGeometry(QtCore.QRect(630, 180, 241, 20))
        self.lineEdit_17.setText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_20.setGeometry(QtCore.QRect(630, 270, 241, 20))
        self.lineEdit_20.setText("")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(460, 180, 91, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_15.setGeometry(QtCore.QRect(630, 120, 241, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(460, 60, 141, 16))
        self.label_13.setObjectName("label_13")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(460, 30, 131, 16))
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(460, 120, 121, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_13.setGeometry(QtCore.QRect(630, 60, 241, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_18.setGeometry(QtCore.QRect(630, 210, 241, 20))
        self.lineEdit_18.setText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(460, 270, 161, 16))
        self.label_20.setObjectName("label_20")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(460, 240, 111, 16))
        self.label_19.setObjectName("label_19")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(460, 150, 131, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_14.setGeometry(QtCore.QRect(630, 90, 241, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.Address = QtWidgets.QTabWidget(self.groupBox)
        self.Address.setGeometry(QtCore.QRect(440, 300, 531, 301))
        self.Address.setObjectName("Address")
        self.Phyical = QtWidgets.QWidget()
        self.Phyical.setObjectName("Phyical")
        self.label_23 = QtWidgets.QLabel(self.Phyical)
        self.label_23.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_23.setObjectName("label_23")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_26.setGeometry(QtCore.QRect(180, 110, 91, 20))
        self.lineEdit_26.setText("")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_27 = QtWidgets.QLabel(self.Phyical)
        self.label_27.setGeometry(QtCore.QRect(280, 110, 91, 16))
        self.label_27.setObjectName("label_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_28.setGeometry(QtCore.QRect(180, 140, 251, 20))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_26 = QtWidgets.QLabel(self.Phyical)
        self.label_26.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_26.setObjectName("label_26")
        self.label_25 = QtWidgets.QLabel(self.Phyical)
        self.label_25.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.label_25.setObjectName("label_25")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_21.setGeometry(QtCore.QRect(180, 20, 41, 20))
        self.lineEdit_21.setText("")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_24.setGeometry(QtCore.QRect(380, 50, 51, 20))
        self.lineEdit_24.setText("")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_22 = QtWidgets.QLabel(self.Phyical)
        self.label_22.setGeometry(QtCore.QRect(230, 20, 91, 16))
        self.label_22.setObjectName("label_22")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_27.setGeometry(QtCore.QRect(370, 110, 61, 20))
        self.lineEdit_27.setText("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_25.setGeometry(QtCore.QRect(180, 80, 251, 20))
        self.lineEdit_25.setText("")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_21 = QtWidgets.QLabel(self.Phyical)
        self.label_21.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_21.setObjectName("label_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_22.setGeometry(QtCore.QRect(290, 20, 141, 20))
        self.lineEdit_22.setText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_24 = QtWidgets.QLabel(self.Phyical)
        self.label_24.setGeometry(QtCore.QRect(230, 50, 151, 16))
        self.label_24.setObjectName("label_24")
        self.label_28 = QtWidgets.QLabel(self.Phyical)
        self.label_28.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_28.setObjectName("label_28")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_23.setGeometry(QtCore.QRect(180, 50, 41, 20))
        self.lineEdit_23.setText("")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.Address.addTab(self.Phyical, "")
        self.Postal = QtWidgets.QWidget()
        self.Postal.setObjectName("Postal")
        self.label_29 = QtWidgets.QLabel(self.Postal)
        self.label_29.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.Postal)
        self.label_30.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.Postal)
        self.label_31.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_31.setObjectName("label_31")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_29.setGeometry(QtCore.QRect(180, 140, 241, 20))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_32 = QtWidgets.QLabel(self.Postal)
        self.label_32.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.Postal)
        self.label_33.setGeometry(QtCore.QRect(230, 20, 91, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.Postal)
        self.label_34.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_34.setObjectName("label_34")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_30.setGeometry(QtCore.QRect(180, 80, 241, 20))
        self.lineEdit_30.setText("")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_31.setGeometry(QtCore.QRect(180, 20, 41, 20))
        self.lineEdit_31.setText("")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_32.setGeometry(QtCore.QRect(310, 20, 121, 20))
        self.lineEdit_32.setText("")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.label_35 = QtWidgets.QLabel(self.Postal)
        self.label_35.setGeometry(QtCore.QRect(280, 110, 91, 16))
        self.label_35.setObjectName("label_35")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_33.setGeometry(QtCore.QRect(370, 110, 51, 20))
        self.lineEdit_33.setText("")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_34.setGeometry(QtCore.QRect(380, 50, 51, 20))
        self.lineEdit_34.setText("")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_35.setGeometry(QtCore.QRect(180, 110, 91, 20))
        self.lineEdit_35.setText("")
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_36.setGeometry(QtCore.QRect(180, 50, 41, 20))
        self.lineEdit_36.setText("")
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.label_36 = QtWidgets.QLabel(self.Postal)
        self.label_36.setGeometry(QtCore.QRect(230, 50, 151, 16))
        self.label_36.setObjectName("label_36")
        self.Address.addTab(self.Postal, "")
        self.Work = QtWidgets.QWidget()
        self.Work.setObjectName("Work")
        self.label_37 = QtWidgets.QLabel(self.Work)
        self.label_37.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.Work)
        self.label_38.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.Work)
        self.label_39.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_39.setObjectName("label_39")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_37.setGeometry(QtCore.QRect(180, 140, 241, 20))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.label_40 = QtWidgets.QLabel(self.Work)
        self.label_40.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.Work)
        self.label_41.setGeometry(QtCore.QRect(230, 20, 91, 16))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.Work)
        self.label_42.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_42.setObjectName("label_42")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_38.setGeometry(QtCore.QRect(180, 80, 241, 20))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_39.setGeometry(QtCore.QRect(180, 20, 41, 20))
        self.lineEdit_39.setText("")
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_40.setGeometry(QtCore.QRect(310, 20, 121, 20))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.label_43 = QtWidgets.QLabel(self.Work)
        self.label_43.setGeometry(QtCore.QRect(280, 110, 91, 16))
        self.label_43.setObjectName("label_43")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_41.setGeometry(QtCore.QRect(370, 110, 51, 20))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_42.setGeometry(QtCore.QRect(340, 50, 101, 20))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_43.setGeometry(QtCore.QRect(180, 110, 91, 20))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_44.setGeometry(QtCore.QRect(180, 50, 41, 20))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.label_44 = QtWidgets.QLabel(self.Work)
        self.label_44.setGeometry(QtCore.QRect(230, 50, 151, 16))
        self.label_44.setObjectName("label_44")
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.lineEdit_37.raise_()
        self.label_40.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.lineEdit_38.raise_()
        self.lineEdit_39.raise_()
        self.lineEdit_40.raise_()
        self.label_43.raise_()
        self.lineEdit_41.raise_()
        self.lineEdit_43.raise_()
        self.lineEdit_44.raise_()
        self.label_44.raise_()
        self.lineEdit_42.raise_()
        self.Address.addTab(self.Work, "")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setGeometry(QtCore.QRect(30, 370, 81, 81))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 210, 111, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(180, 210, 241, 20))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.dateEdit_10 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_10.setGeometry(QtCore.QRect(180, 270, 241, 22))
        self.dateEdit_10.setCalendarPopup(True)
        self.dateEdit_10.setObjectName("dateEdit_10")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 91, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 150, 241, 20))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 270, 81, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_11.setGeometry(QtCore.QRect(180, 300, 151, 20))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(340, 180, 41, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(180, 240, 241, 20))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 131, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 240, 111, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(390, 180, 31, 20))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 300, 131, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(180, 180, 151, 20))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_1.raise_()
        self.lineEdit_1.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.label_4.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_12.raise_()
        self.lineEdit_19.raise_()
        self.label_14.raise_()
        self.label_18.raise_()
        self.lineEdit_16.raise_()
        self.lineEdit_17.raise_()
        self.lineEdit_20.raise_()
        self.label_17.raise_()
        self.lineEdit_15.raise_()
        self.label_13.raise_()
        self.label_12.raise_()
        self.label_15.raise_()
        self.lineEdit_13.raise_()
        self.lineEdit_18.raise_()
        self.label_20.raise_()
        self.label_19.raise_()
        self.label_16.raise_()
        self.lineEdit_14.raise_()
        self.lcdNumber.raise_()
        self.label_8.raise_()
        self.lineEdit_8.raise_()
        self.dateEdit_10.raise_()
        self.label_5.raise_()
        self.lineEdit_5.raise_()
        self.label_10.raise_()
        self.lineEdit_11.raise_()
        self.label_7.raise_()
        self.lineEdit_9.raise_()
        self.label_6.raise_()
        self.label_9.raise_()
        self.lineEdit_7.raise_()
        self.label_11.raise_()
        self.lineEdit_6.raise_()
        self.Address.raise_()
        self.MainTabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 1081, 761))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_46.setGeometry(QtCore.QRect(240, 120, 221, 21))
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.label_55 = QtWidgets.QLabel(self.groupBox_2)
        self.label_55.setGeometry(QtCore.QRect(510, 180, 211, 17))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.groupBox_2)
        self.label_56.setGeometry(QtCore.QRect(20, 60, 54, 17))
        self.label_56.setObjectName("label_56")
        self.label_49 = QtWidgets.QLabel(self.groupBox_2)
        self.label_49.setGeometry(QtCore.QRect(20, 210, 181, 17))
        self.label_49.setObjectName("label_49")
        self.label_46 = QtWidgets.QLabel(self.groupBox_2)
        self.label_46.setGeometry(QtCore.QRect(20, 120, 121, 17))
        self.label_46.setObjectName("label_46")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_48.setGeometry(QtCore.QRect(240, 180, 221, 21))
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.label_53 = QtWidgets.QLabel(self.groupBox_2)
        self.label_53.setGeometry(QtCore.QRect(510, 120, 131, 17))
        self.label_53.setObjectName("label_53")
        self.label_48 = QtWidgets.QLabel(self.groupBox_2)
        self.label_48.setGeometry(QtCore.QRect(20, 180, 111, 17))
        self.label_48.setObjectName("label_48")
        self.label_47 = QtWidgets.QLabel(self.groupBox_2)
        self.label_47.setGeometry(QtCore.QRect(20, 150, 141, 17))
        self.label_47.setObjectName("label_47")
        self.label_51 = QtWidgets.QLabel(self.groupBox_2)
        self.label_51.setGeometry(QtCore.QRect(510, 60, 181, 17))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.groupBox_2)
        self.label_52.setGeometry(QtCore.QRect(510, 90, 161, 17))
        self.label_52.setObjectName("label_52")
        self.label_50 = QtWidgets.QLabel(self.groupBox_2)
        self.label_50.setGeometry(QtCore.QRect(20, 240, 221, 17))
        self.label_50.setObjectName("label_50")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_47.setGeometry(QtCore.QRect(240, 150, 221, 21))
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.label_45 = QtWidgets.QLabel(self.groupBox_2)
        self.label_45.setGeometry(QtCore.QRect(20, 90, 111, 17))
        self.label_45.setObjectName("label_45")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_45.setGeometry(QtCore.QRect(240, 90, 221, 21))
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.label_54 = QtWidgets.QLabel(self.groupBox_2)
        self.label_54.setGeometry(QtCore.QRect(510, 150, 221, 17))
        self.label_54.setObjectName("label_54")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_50.setGeometry(QtCore.QRect(240, 240, 221, 21))
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_49.setGeometry(QtCore.QRect(240, 210, 221, 21))
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_51.setGeometry(QtCore.QRect(730, 60, 221, 21))
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_52.setGeometry(QtCore.QRect(730, 90, 221, 21))
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_53.setGeometry(QtCore.QRect(730, 120, 221, 21))
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.lineEdit_54 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_54.setGeometry(QtCore.QRect(730, 150, 221, 21))
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.lineEdit_55 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_55.setGeometry(QtCore.QRect(730, 180, 221, 21))
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.label_80 = QtWidgets.QLabel(self.groupBox_2)
        self.label_80.setGeometry(QtCore.QRect(20, 30, 181, 17))
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.groupBox_2)
        self.label_81.setGeometry(QtCore.QRect(130, 20, 301, 17))
        self.label_81.setObjectName("label_81")
        self.label_84 = QtWidgets.QLabel(self.groupBox_2)
        self.label_84.setGeometry(QtCore.QRect(510, 30, 191, 17))
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.groupBox_2)
        self.label_85.setGeometry(QtCore.QRect(640, 20, 301, 17))
        self.label_85.setObjectName("label_85")
        self.label_82 = QtWidgets.QLabel(self.groupBox_2)
        self.label_82.setGeometry(QtCore.QRect(20, 280, 71, 17))
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.groupBox_2)
        self.label_83.setGeometry(QtCore.QRect(110, 270, 381, 20))
        self.label_83.setObjectName("label_83")
        self.label_62 = QtWidgets.QLabel(self.groupBox_2)
        self.label_62.setGeometry(QtCore.QRect(20, 300, 111, 17))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.groupBox_2)
        self.label_63.setGeometry(QtCore.QRect(20, 330, 111, 17))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.groupBox_2)
        self.label_64.setGeometry(QtCore.QRect(20, 360, 111, 17))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.groupBox_2)
        self.label_65.setGeometry(QtCore.QRect(20, 390, 111, 17))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.groupBox_2)
        self.label_66.setGeometry(QtCore.QRect(20, 420, 111, 17))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.groupBox_2)
        self.label_67.setGeometry(QtCore.QRect(20, 450, 111, 17))
        self.label_67.setObjectName("label_67")
        self.lineEdit_62 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_62.setGeometry(QtCore.QRect(210, 300, 221, 21))
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.lineEdit_63 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_63.setGeometry(QtCore.QRect(210, 330, 221, 21))
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.lineEdit_64 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_64.setGeometry(QtCore.QRect(210, 360, 221, 21))
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.lineEdit_65 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_65.setGeometry(QtCore.QRect(210, 390, 221, 21))
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.lineEdit_66 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_66.setGeometry(QtCore.QRect(210, 420, 221, 21))
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.lineEdit_67 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_67.setGeometry(QtCore.QRect(210, 450, 221, 21))
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.label_88 = QtWidgets.QLabel(self.groupBox_2)
        self.label_88.setGeometry(QtCore.QRect(750, 270, 311, 20))
        self.label_88.setObjectName("label_88")
        self.label_86 = QtWidgets.QLabel(self.groupBox_2)
        self.label_86.setGeometry(QtCore.QRect(510, 280, 231, 16))
        self.label_86.setObjectName("label_86")
        self.label_70 = QtWidgets.QLabel(self.groupBox_2)
        self.label_70.setGeometry(QtCore.QRect(510, 300, 191, 17))
        self.label_70.setObjectName("label_70")
        self.lineEdit_70 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_70.setGeometry(QtCore.QRect(720, 300, 221, 21))
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.lineEdit_71 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_71.setGeometry(QtCore.QRect(720, 330, 221, 21))
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.lineEdit_72 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_72.setGeometry(QtCore.QRect(720, 360, 221, 21))
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.lineEdit_73 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_73.setGeometry(QtCore.QRect(720, 390, 221, 21))
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.label_71 = QtWidgets.QLabel(self.groupBox_2)
        self.label_71.setGeometry(QtCore.QRect(510, 330, 201, 17))
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.groupBox_2)
        self.label_72.setGeometry(QtCore.QRect(510, 360, 191, 17))
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.groupBox_2)
        self.label_73.setGeometry(QtCore.QRect(510, 390, 221, 17))
        self.label_73.setObjectName("label_73")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(130, 610, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 610, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 610, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 660, 721, 81))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.lineEdit_74 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_74.setGeometry(QtCore.QRect(240, 60, 221, 21))
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.MainTabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.MainTabs.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_14.setGeometry(QtCore.QRect(90, 10, 87, 29))
        self.pushButton_14.setObjectName("pushButton_14")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 60, 751, 121))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(3)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_15.setGeometry(QtCore.QRect(0, 10, 87, 29))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_16.setGeometry(QtCore.QRect(180, 10, 87, 29))
        self.pushButton_16.setObjectName("pushButton_16")
        self.MainTabs.addTab(self.tab_4, "")
        self.TabIndemnity = QtWidgets.QWidget()
        self.TabIndemnity.setObjectName("TabIndemnity")
        self.pushButton_17 = QtWidgets.QPushButton(self.TabIndemnity)
        self.pushButton_17.setGeometry(QtCore.QRect(180, 10, 87, 29))
        self.pushButton_17.setObjectName("pushButton_17")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.TabIndemnity)
        self.tableWidget_7.setGeometry(QtCore.QRect(0, 60, 751, 121))
        self.tableWidget_7.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(3)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        self.pushButton_18 = QtWidgets.QPushButton(self.TabIndemnity)
        self.pushButton_18.setGeometry(QtCore.QRect(0, 10, 87, 29))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.TabIndemnity)
        self.pushButton_19.setGeometry(QtCore.QRect(90, 10, 87, 29))
        self.pushButton_19.setObjectName("pushButton_19")
        self.MainTabs.addTab(self.TabIndemnity, "")
        self.TabExpirations = QtWidgets.QWidget()
        self.TabExpirations.setObjectName("TabExpirations")
        self.pushButton_20 = QtWidgets.QPushButton(self.TabExpirations)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.TabExpirations)
        self.pushButton_21.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.TabExpirations)
        self.pushButton_22.setGeometry(QtCore.QRect(190, 10, 87, 29))
        self.pushButton_22.setObjectName("pushButton_22")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.TabExpirations)
        self.tableWidget_8.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget_8.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(3)
        self.tableWidget_8.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_8.setHorizontalHeaderItem(2, item)
        self.MainTabs.addTab(self.TabExpirations, "")
        self.TabLinkedClients = QtWidgets.QWidget()
        self.TabLinkedClients.setObjectName("TabLinkedClients")
        self.pushButton_23 = QtWidgets.QPushButton(self.TabLinkedClients)
        self.pushButton_23.setGeometry(QtCore.QRect(0, 0, 87, 29))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.TabLinkedClients)
        self.pushButton_24.setGeometry(QtCore.QRect(90, 0, 87, 29))
        self.pushButton_24.setObjectName("pushButton_24")
        self.tableWidget_9 = QtWidgets.QTableWidget(self.TabLinkedClients)
        self.tableWidget_9.setGeometry(QtCore.QRect(0, 50, 751, 121))
        self.tableWidget_9.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(3)
        self.tableWidget_9.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        self.pushButton_25 = QtWidgets.QPushButton(self.TabLinkedClients)
        self.pushButton_25.setGeometry(QtCore.QRect(180, 0, 87, 29))
        self.pushButton_25.setObjectName("pushButton_25")
        self.MainTabs.addTab(self.TabLinkedClients, "")
        self.TabUserDefinedFields = QtWidgets.QWidget()
        self.TabUserDefinedFields.setObjectName("TabUserDefinedFields")
        self.label_149 = QtWidgets.QLabel(self.TabUserDefinedFields)
        self.label_149.setGeometry(QtCore.QRect(10, 160, 161, 17))
        self.label_149.setObjectName("label_149")
        self.lineEdit_131 = QtWidgets.QLineEdit(self.TabUserDefinedFields)
        self.lineEdit_131.setGeometry(QtCore.QRect(230, 100, 741, 21))
        self.lineEdit_131.setObjectName("lineEdit_131")
        self.lineEdit_132 = QtWidgets.QLineEdit(self.TabUserDefinedFields)
        self.lineEdit_132.setGeometry(QtCore.QRect(230, 130, 741, 21))
        self.lineEdit_132.setObjectName("lineEdit_132")
        self.label_150 = QtWidgets.QLabel(self.TabUserDefinedFields)
        self.label_150.setGeometry(QtCore.QRect(10, 100, 161, 17))
        self.label_150.setObjectName("label_150")
        self.lineEdit_134 = QtWidgets.QLineEdit(self.TabUserDefinedFields)
        self.lineEdit_134.setGeometry(QtCore.QRect(230, 220, 741, 21))
        self.lineEdit_134.setObjectName("lineEdit_134")
        self.lineEdit_135 = QtWidgets.QLineEdit(self.TabUserDefinedFields)
        self.lineEdit_135.setGeometry(QtCore.QRect(230, 70, 741, 21))
        self.lineEdit_135.setObjectName("lineEdit_135")
        self.lineEdit_136 = QtWidgets.QLineEdit(self.TabUserDefinedFields)
        self.lineEdit_136.setGeometry(QtCore.QRect(230, 160, 741, 21))
        self.lineEdit_136.setObjectName("lineEdit_136")
        self.label_151 = QtWidgets.QLabel(self.TabUserDefinedFields)
        self.label_151.setGeometry(QtCore.QRect(10, 190, 171, 17))
        self.label_151.setObjectName("label_151")
        self.label_152 = QtWidgets.QLabel(self.TabUserDefinedFields)
        self.label_152.setGeometry(QtCore.QRect(10, 250, 221, 17))
        self.label_152.setObjectName("label_152")
        self.lineEdit_137 = QtWidgets.QLineEdit(self.TabUserDefinedFields)
        self.lineEdit_137.setGeometry(QtCore.QRect(230, 190, 741, 21))
        self.lineEdit_137.setObjectName("lineEdit_137")
        self.label_153 = QtWidgets.QLabel(self.TabUserDefinedFields)
        self.label_153.setGeometry(QtCore.QRect(10, 130, 171, 17))
        self.label_153.setObjectName("label_153")
        self.label_154 = QtWidgets.QLabel(self.TabUserDefinedFields)
        self.label_154.setGeometry(QtCore.QRect(10, 220, 181, 17))
        self.label_154.setObjectName("label_154")
        self.label_155 = QtWidgets.QLabel(self.TabUserDefinedFields)
        self.label_155.setGeometry(QtCore.QRect(10, 70, 181, 17))
        self.label_155.setObjectName("label_155")
        self.pushButton_26 = QtWidgets.QPushButton(self.TabUserDefinedFields)
        self.pushButton_26.setGeometry(QtCore.QRect(10, 10, 121, 29))
        self.pushButton_26.setObjectName("pushButton_26")
        self.checkBox = QtWidgets.QCheckBox(self.TabUserDefinedFields)
        self.checkBox.setGeometry(QtCore.QRect(340, 250, 113, 29))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.TabUserDefinedFields)
        self.checkBox_2.setGeometry(QtCore.QRect(340, 280, 113, 29))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.TabUserDefinedFields)
        self.checkBox_3.setGeometry(QtCore.QRect(340, 310, 113, 29))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.TabUserDefinedFields)
        self.checkBox_4.setGeometry(QtCore.QRect(340, 340, 113, 29))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.TabUserDefinedFields)
        self.checkBox_5.setGeometry(QtCore.QRect(340, 370, 113, 29))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_156 = QtWidgets.QLabel(self.TabUserDefinedFields)
        self.label_156.setGeometry(QtCore.QRect(10, 310, 321, 17))
        self.label_156.setObjectName("label_156")
        self.label_157 = QtWidgets.QLabel(self.TabUserDefinedFields)
        self.label_157.setGeometry(QtCore.QRect(10, 340, 221, 17))
        self.label_157.setObjectName("label_157")
        self.label_158 = QtWidgets.QLabel(self.TabUserDefinedFields)
        self.label_158.setGeometry(QtCore.QRect(10, 370, 221, 17))
        self.label_158.setObjectName("label_158")
        self.label_159 = QtWidgets.QLabel(self.TabUserDefinedFields)
        self.label_159.setGeometry(QtCore.QRect(10, 280, 321, 17))
        self.label_159.setObjectName("label_159")
        self.MainTabs.addTab(self.TabUserDefinedFields, "")
        self.TabActivities = QtWidgets.QWidget()
        self.TabActivities.setObjectName("TabActivities")
        self.pushButton_27 = QtWidgets.QPushButton(self.TabActivities)
        self.pushButton_27.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.TabActivities)
        self.pushButton_28.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.TabActivities)
        self.pushButton_29.setGeometry(QtCore.QRect(190, 10, 87, 29))
        self.pushButton_29.setObjectName("pushButton_29")
        self.tableWidget_10 = QtWidgets.QTableWidget(self.TabActivities)
        self.tableWidget_10.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget_10.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(4)
        self.tableWidget_10.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(3, item)
        self.MainTabs.addTab(self.TabActivities, "")
        self.TabAdministration = QtWidgets.QWidget()
        self.TabAdministration.setObjectName("TabAdministration")
        self.label_160 = QtWidgets.QLabel(self.TabAdministration)
        self.label_160.setGeometry(QtCore.QRect(10, 40, 161, 17))
        self.label_160.setObjectName("label_160")
        self.label_161 = QtWidgets.QLabel(self.TabAdministration)
        self.label_161.setGeometry(QtCore.QRect(10, 100, 161, 17))
        self.label_161.setObjectName("label_161")
        self.label_162 = QtWidgets.QLabel(self.TabAdministration)
        self.label_162.setGeometry(QtCore.QRect(10, 70, 171, 17))
        self.label_162.setObjectName("label_162")
        self.label_163 = QtWidgets.QLabel(self.TabAdministration)
        self.label_163.setGeometry(QtCore.QRect(500, 10, 231, 17))
        self.label_163.setObjectName("label_163")
        self.label_164 = QtWidgets.QLabel(self.TabAdministration)
        self.label_164.setGeometry(QtCore.QRect(10, 10, 181, 17))
        self.label_164.setObjectName("label_164")
        self.lineEdit_133 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_133.setGeometry(QtCore.QRect(240, 40, 221, 21))
        self.lineEdit_133.setObjectName("lineEdit_133")
        self.lineEdit_138 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_138.setGeometry(QtCore.QRect(240, 70, 221, 21))
        self.lineEdit_138.setObjectName("lineEdit_138")
        self.lineEdit_139 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_139.setGeometry(QtCore.QRect(240, 10, 221, 21))
        self.lineEdit_139.setObjectName("lineEdit_139")
        self.lineEdit_140 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_140.setGeometry(QtCore.QRect(240, 100, 221, 21))
        self.lineEdit_140.setObjectName("lineEdit_140")
        self.lineEdit_141 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_141.setGeometry(QtCore.QRect(760, 10, 221, 21))
        self.lineEdit_141.setObjectName("lineEdit_141")
        self.MainTabs.addTab(self.TabAdministration, "")
        self.TabAttachments = QtWidgets.QWidget()
        self.TabAttachments.setObjectName("TabAttachments")
        self.pushButton_30 = QtWidgets.QPushButton(self.TabAttachments)
        self.pushButton_30.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.TabAttachments)
        self.pushButton_31.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.TabAttachments)
        self.pushButton_32.setGeometry(QtCore.QRect(190, 10, 87, 29))
        self.pushButton_32.setObjectName("pushButton_32")
        self.tableWidget_11 = QtWidgets.QTableWidget(self.TabAttachments)
        self.tableWidget_11.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget_11.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_11.setObjectName("tableWidget_11")
        self.tableWidget_11.setColumnCount(3)
        self.tableWidget_11.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_11.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_11.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_11.setHorizontalHeaderItem(2, item)
        self.pushButton_33 = QtWidgets.QPushButton(self.TabAttachments)
        self.pushButton_33.setGeometry(QtCore.QRect(280, 10, 87, 29))
        self.pushButton_33.setObjectName("pushButton_33")
        self.MainTabs.addTab(self.TabAttachments, "")
        self.TabVIP = QtWidgets.QWidget()
        self.TabVIP.setObjectName("TabVIP")
        self.tableWidget_12 = QtWidgets.QTableWidget(self.TabVIP)
        self.tableWidget_12.setGeometry(QtCore.QRect(10, 50, 751, 121))
        self.tableWidget_12.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_12.setObjectName("tableWidget_12")
        self.tableWidget_12.setColumnCount(8)
        self.tableWidget_12.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_12.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_12.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_12.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(7, item)
        self.dateEdit = QtWidgets.QDateEdit(self.TabVIP)
        self.dateEdit.setGeometry(QtCore.QRect(60, 10, 119, 28))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.TabVIP)
        self.dateEdit_2.setGeometry(QtCore.QRect(240, 10, 121, 28))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_165 = QtWidgets.QLabel(self.TabVIP)
        self.label_165.setGeometry(QtCore.QRect(10, 20, 41, 17))
        self.label_165.setObjectName("label_165")
        self.label_166 = QtWidgets.QLabel(self.TabVIP)
        self.label_166.setGeometry(QtCore.QRect(190, 20, 41, 17))
        self.label_166.setObjectName("label_166")
        self.pushButton_34 = QtWidgets.QPushButton(self.TabVIP)
        self.pushButton_34.setGeometry(QtCore.QRect(380, 10, 111, 29))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.TabVIP)
        self.pushButton_35.setGeometry(QtCore.QRect(506, 10, 131, 29))
        self.pushButton_35.setObjectName("pushButton_35")
        self.MainTabs.addTab(self.TabVIP, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_9)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 1111, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.pushButton_36 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_36.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_37.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_38.setGeometry(QtCore.QRect(190, 10, 87, 29))
        self.pushButton_38.setObjectName("pushButton_38")
        self.tableWidget_13 = QtWidgets.QTableWidget(self.tab_10)
        self.tableWidget_13.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget_13.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_13.setObjectName("tableWidget_13")
        self.tableWidget_13.setColumnCount(9)
        self.tableWidget_13.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_13.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_13.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_13.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.pushButton_39 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_39.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_40.setGeometry(QtCore.QRect(190, 10, 87, 29))
        self.pushButton_40.setObjectName("pushButton_40")
        self.tableWidget_14 = QtWidgets.QTableWidget(self.tab_11)
        self.tableWidget_14.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget_14.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_14.setObjectName("tableWidget_14")
        self.tableWidget_14.setColumnCount(3)
        self.tableWidget_14.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_14.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_14.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_14.setHorizontalHeaderItem(2, item)
        self.pushButton_41 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_41.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_42.setGeometry(QtCore.QRect(280, 10, 87, 29))
        self.pushButton_42.setObjectName("pushButton_42")
        self.tabWidget.addTab(self.tab_11, "")
        self.MainTabs.addTab(self.tab_9, "")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(70, 710, 721, 81))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 650, 781, 41))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 777, 37))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.InsertData)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 10, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 10, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.MainTabs.setCurrentIndex(0)
        self.Address.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Candidate Details"))
        self.label_1.setText(_translate("MainWindow", "Title:"))
        self.label_2.setText(_translate("MainWindow", "First Name:"))
        self.label_3.setText(_translate("MainWindow", "Second Name:"))
        self.label_4.setText(_translate("MainWindow", "Last Name:"))
        self.label_14.setText(_translate("MainWindow", "Telephone Work:"))
        self.label_18.setText(_translate("MainWindow", "SANC Number:"))
        self.label_17.setText(_translate("MainWindow", "Category:"))
        self.label_13.setText(_translate("MainWindow", "Telephone Home:"))
        self.label_12.setText(_translate("MainWindow", "Folder (Status):"))
        self.label_15.setText(_translate("MainWindow", "Telephone Cell:"))
        self.label_20.setText(_translate("MainWindow", "Employment Equity:"))
        self.label_19.setText(_translate("MainWindow", "Marital Status:"))
        self.label_16.setText(_translate("MainWindow", "Email Address:"))
        self.label_23.setText(_translate("MainWindow", "Street Nr:"))
        self.label_27.setText(_translate("MainWindow", "Postal Code:"))
        self.lineEdit_28.setText(_translate("MainWindow", "South Africa"))
        self.label_26.setText(_translate("MainWindow", "City/Town:"))
        self.label_25.setText(_translate("MainWindow", "Suburb/District:"))
        self.label_22.setText(_translate("MainWindow", "Complex:"))
        self.label_21.setText(_translate("MainWindow", "Unit Nr:"))
        self.label_24.setText(_translate("MainWindow", "Street Name/Farm:"))
        self.label_28.setText(_translate("MainWindow", "Country/Region:"))
        self.Address.setTabText(self.Address.indexOf(self.Phyical), _translate("MainWindow", "Phyical"))
        self.label_29.setText(_translate("MainWindow", "Suburb/District:"))
        self.label_30.setText(_translate("MainWindow", "City/Town:"))
        self.label_31.setText(_translate("MainWindow", "Country/Region:"))
        self.lineEdit_29.setText(_translate("MainWindow", "South Africa"))
        self.label_32.setText(_translate("MainWindow", "Unit Nr:"))
        self.label_33.setText(_translate("MainWindow", "Complex:"))
        self.label_34.setText(_translate("MainWindow", "Street Nr:"))
        self.label_35.setText(_translate("MainWindow", "Postal Code:"))
        self.label_36.setText(_translate("MainWindow", "Street Name/Farm:"))
        self.Address.setTabText(self.Address.indexOf(self.Postal), _translate("MainWindow", "Postal"))
        self.label_37.setText(_translate("MainWindow", "Suburb/District:"))
        self.label_38.setText(_translate("MainWindow", "City/Town:"))
        self.label_39.setText(_translate("MainWindow", "Country/Region:"))
        self.lineEdit_37.setText(_translate("MainWindow", "South Africa"))
        self.label_40.setText(_translate("MainWindow", "Unit Nr:"))
        self.label_41.setText(_translate("MainWindow", "Complex:"))
        self.label_42.setText(_translate("MainWindow", "Street Nr:"))
        self.lineEdit_38.setText(_translate("MainWindow", "Strand"))
        self.lineEdit_40.setText(_translate("MainWindow", "Medx"))
        self.label_43.setText(_translate("MainWindow", "Postal Code:"))
        self.lineEdit_41.setText(_translate("MainWindow", "7140"))
        self.lineEdit_42.setText(_translate("MainWindow", "Main Road"))
        self.lineEdit_43.setText(_translate("MainWindow", "Cape Town"))
        self.lineEdit_44.setText(_translate("MainWindow", "36"))
        self.label_44.setText(_translate("MainWindow", "Street Name/Farm:"))
        self.Address.setTabText(self.Address.indexOf(self.Work), _translate("MainWindow", "Work"))
        self.label_8.setText(_translate("MainWindow", "Passport Country:"))
        self.label_5.setText(_translate("MainWindow", "Initials:"))
        self.label_10.setText(_translate("MainWindow", "Date of Birth:"))
        self.label_7.setText(_translate("MainWindow", "Age:"))
        self.label_6.setText(_translate("MainWindow", "Identification Number:"))
        self.label_9.setText(_translate("MainWindow", "Passport Number:"))
        self.label_11.setText(_translate("MainWindow", "Gender:"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab), _translate("MainWindow", "General"))
        self.label_55.setText(_translate("MainWindow", "Repayments occur per:"))
        self.label_56.setText(_translate("MainWindow", "Bank:"))
        self.label_49.setText(_translate("MainWindow", "Account Holder Name:"))
        self.label_46.setText(_translate("MainWindow", "Account Name:"))
        self.label_53.setText(_translate("MainWindow", "Payment Type:"))
        self.label_48.setText(_translate("MainWindow", "Account Type:"))
        self.label_47.setText(_translate("MainWindow", "Account Number:"))
        self.label_51.setText(_translate("MainWindow", "Registerd:"))
        self.label_52.setText(_translate("MainWindow", "Payment Frequency:"))
        self.label_50.setText(_translate("MainWindow", "Account Holder Relationship:"))
        self.label_45.setText(_translate("MainWindow", "Branch Code:"))
        self.label_54.setText(_translate("MainWindow", "Maximum Payback Amount:"))
        self.label_80.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">Financial Details</span></p></body></html>"))
        self.label_81.setText(_translate("MainWindow", "________________________________________________________"))
        self.label_84.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">Account Information</span></p></body></html>"))
        self.label_85.setText(_translate("MainWindow", "________________________________________________________"))
        self.label_82.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">Tax</span></p></body></html>"))
        self.label_83.setText(_translate("MainWindow", "_______________________________________________________________________"))
        self.label_62.setText(_translate("MainWindow", "Tax Status:"))
        self.label_63.setText(_translate("MainWindow", "Income Tax nr:"))
        self.label_64.setText(_translate("MainWindow", "Engaged:"))
        self.label_65.setText(_translate("MainWindow", "Discharged:"))
        self.label_66.setText(_translate("MainWindow", "UIF Registrerd:"))
        self.label_67.setText(_translate("MainWindow", "UIF Status:"))
        self.label_88.setText(_translate("MainWindow", "___________________________________"))
        self.label_86.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">Medical / Pension / Provident</span></p></body></html>"))
        self.label_70.setText(_translate("MainWindow", "Medical Aid Start Date:"))
        self.label_71.setText(_translate("MainWindow", "Medical Aid Dependants:"))
        self.label_72.setText(_translate("MainWindow", "Pension Fund Start Date:"))
        self.label_73.setText(_translate("MainWindow", "Provident Fund Start Date:"))
        self.pushButton_4.setText(_translate("MainWindow", "Update"))
        self.pushButton_5.setText(_translate("MainWindow", "Delete"))
        self.pushButton_6.setText(_translate("MainWindow", "Add"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab_2), _translate("MainWindow", "Payroll"))
        self.pushButton_7.setText(_translate("MainWindow", "Add"))
        self.pushButton_8.setText(_translate("MainWindow", "Delete"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Code"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Description"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab_3), _translate("MainWindow", "Qualifications"))
        self.pushButton_14.setText(_translate("MainWindow", "Update"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CandidateID"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "YourID"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SANCReceipt"))
        self.pushButton_15.setText(_translate("MainWindow", "Add"))
        self.pushButton_16.setText(_translate("MainWindow", "Delete"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab_4), _translate("MainWindow", "SANC Receipts"))
        self.pushButton_17.setText(_translate("MainWindow", "Delete"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Company"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Policy Number"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expiry Date"))
        self.pushButton_18.setText(_translate("MainWindow", "Add"))
        self.pushButton_19.setText(_translate("MainWindow", "Update"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabIndemnity), _translate("MainWindow", "Indemnity"))
        self.pushButton_20.setText(_translate("MainWindow", "Add"))
        self.pushButton_21.setText(_translate("MainWindow", "Update"))
        self.pushButton_22.setText(_translate("MainWindow", "Delete"))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget_8.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Reference Number"))
        item = self.tableWidget_8.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expiry Date"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabExpirations), _translate("MainWindow", "Expirations"))
        self.pushButton_23.setText(_translate("MainWindow", "Add"))
        self.pushButton_24.setText(_translate("MainWindow", "Update"))
        item = self.tableWidget_9.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Preferred"))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client"))
        item = self.tableWidget_9.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Candidate Integration Code"))
        self.pushButton_25.setText(_translate("MainWindow", "Delete"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabLinkedClients), _translate("MainWindow", "Linked Clients"))
        self.label_149.setText(_translate("MainWindow", "Extra Qualifications"))
        self.label_150.setText(_translate("MainWindow", "Extra Qualifications"))
        self.label_151.setText(_translate("MainWindow", "Previous Work Places"))
        self.label_152.setText(_translate("MainWindow", "Old Contract"))
        self.label_153.setText(_translate("MainWindow", "Extra Qualifications"))
        self.label_154.setText(_translate("MainWindow", "Dislikes"))
        self.label_155.setText(_translate("MainWindow", "Qualifications"))
        self.pushButton_26.setText(_translate("MainWindow", "New Field..."))
        self.label_156.setText(_translate("MainWindow", "Proof of Hepatitis B Injection October 2014"))
        self.label_157.setText(_translate("MainWindow", "Criminal Check"))
        self.label_158.setText(_translate("MainWindow", "Reference Check"))
        self.label_159.setText(_translate("MainWindow", "New Med X Contract October 2014"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabUserDefinedFields), _translate("MainWindow", "User-Defined Fields"))
        self.pushButton_27.setText(_translate("MainWindow", "Update"))
        self.pushButton_28.setText(_translate("MainWindow", "Add"))
        self.pushButton_29.setText(_translate("MainWindow", "Delete"))
        item = self.tableWidget_10.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Occurred At"))
        item = self.tableWidget_10.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Activity Type"))
        item = self.tableWidget_10.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "User"))
        item = self.tableWidget_10.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Note"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabActivities), _translate("MainWindow", "Activities"))
        self.label_160.setText(_translate("MainWindow", "Created On:"))
        self.label_161.setText(_translate("MainWindow", "Last Updated On:"))
        self.label_162.setText(_translate("MainWindow", "Last Updated By:"))
        self.label_163.setText(_translate("MainWindow", "Last Sanc Warning SMS Sent:"))
        self.label_164.setText(_translate("MainWindow", "Created By:"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabAdministration), _translate("MainWindow", "Administration"))
        self.pushButton_30.setText(_translate("MainWindow", "Update"))
        self.pushButton_31.setText(_translate("MainWindow", "Add"))
        self.pushButton_32.setText(_translate("MainWindow", "Delete"))
        item = self.tableWidget_11.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "FileName"))
        item = self.tableWidget_11.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Descrition"))
        item = self.tableWidget_11.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NodifiedDate"))
        self.pushButton_33.setText(_translate("MainWindow", "Open"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabAttachments), _translate("MainWindow", "Attachments"))
        item = self.tableWidget_12.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DatePaid"))
        item = self.tableWidget_12.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PeriodEndDate"))
        item = self.tableWidget_12.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NodifiedDate"))
        item = self.tableWidget_12.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "GrossEarnings"))
        item = self.tableWidget_12.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Paye"))
        item = self.tableWidget_12.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Uif"))
        item = self.tableWidget_12.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Loans"))
        item = self.tableWidget_12.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Other"))
        self.label_165.setText(_translate("MainWindow", "From:"))
        self.label_166.setText(_translate("MainWindow", "To:"))
        self.pushButton_34.setText(_translate("MainWindow", "Apply Filter"))
        self.pushButton_35.setText(_translate("MainWindow", "Clear Filter"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabVIP), _translate("MainWindow", "VIP"))
        self.pushButton_36.setText(_translate("MainWindow", "Update"))
        self.pushButton_37.setText(_translate("MainWindow", "Add"))
        self.pushButton_38.setText(_translate("MainWindow", "Delete"))
        item = self.tableWidget_13.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Course Date"))
        item = self.tableWidget_13.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Code"))
        item = self.tableWidget_13.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Candidate Integration Code"))
        item = self.tableWidget_13.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CanidateID"))
        item = self.tableWidget_13.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_13.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "TrainingCourseCode"))
        item = self.tableWidget_13.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "CourseDate"))
        item = self.tableWidget_13.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "ClientID"))
        item = self.tableWidget_13.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Created"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "Completed Training"))
        self.pushButton_39.setText(_translate("MainWindow", "Update"))
        self.pushButton_40.setText(_translate("MainWindow", "Delete"))
        item = self.tableWidget_14.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Course"))
        item = self.tableWidget_14.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Module"))
        item = self.tableWidget_14.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        self.pushButton_41.setText(_translate("MainWindow", "Add"))
        self.pushButton_42.setText(_translate("MainWindow", "Report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Assigned Modules"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab_9), _translate("MainWindow", "Training"))
        self.pushButton.setText(_translate("MainWindow", "Add"))
        self.pushButton_2.setText(_translate("MainWindow", "Update"))
        self.pushButton_3.setText(_translate("MainWindow", "Delete"))



    def InsertData(self):
        con = pymysql.connect(host='127.0.0.1',
                             user='pierreb',
                             password='Springboks2017',                             
                             db='medx',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
        with con:
                cur = con.cursor()
                cur.execute("INSERT INTO candidate_table(Title, FirstName, SecondName, LastName, Initial, IdentificationNumber, PassportCountryCode, PassportNumber, DateOfBirth, GenderID, CandidateFolderID, TelephoneHome, TelephoneWork, TelephoneCell, EmailAddress, CandidateCategoryID, SANCNumber, MaritalStatusID, EmploymentEquityID, PhysicalAddressUnitNumber, PhysicalAddressComplex, PhysicalAddressStreetNumber, PhysicalAddressStreetName, PhysicalAddressSuburb, PhysicalAddressCity, PhysicalAddressPostalCode, PhysicalAddressCountry, PostalAddressPostalNumber, PostalAddressTypeOfService, PostalAddressStreetNumber, PostalAddressStreetName, PostalAddressSuburb, PostalAddressCity, PostalAddressPostalCode, PostalAddressCountry, WorkAddressUnitNumber, WorkAddressComplex, WorkAddressStreetNumber, WorkAddressStreetName, WorkAddressSuburb, WorkAddressCity, WorkAddressPostalCode, WorkAddressCountry, BankName, BankBranchCode, BankAccountName, BankAccountNumber, BankAccountTypeID, AccountHolderName)"
                            "VALUES('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s')" %(''.join(self.lineEdit_1.text()),
                                                                                    ''.join(self.lineEdit_2.text()),
                                                                                    ''.join(self.lineEdit_3.text()),
                                                                                    ''.join(self.lineEdit_4.text()),
                                                                                    ''.join(self.lineEdit_5.text()),
                                                                                    ''.join(self.lineEdit_6.text()),
                                                                                    ''.join(self.lineEdit_8.text()),
                                                                                    ''.join(self.lineEdit_9.text()),
                                                                                    ''.join(self.dateEdit_10.text()),
                                                                                    ''.join(self.lineEdit_11.text()),
                                                                                    ''.join(self.lineEdit_12.text()),
                                                                                    ''.join(self.lineEdit_13.text()),
                                                                                    ''.join(self.lineEdit_14.text()),
                                                                                    ''.join(self.lineEdit_15.text()),
                                                                                    ''.join(self.lineEdit_16.text()),
                                                                                    ''.join(self.lineEdit_17.text()),
                                                                                    ''.join(self.lineEdit_18.text()),
                                                                                    ''.join(self.lineEdit_19.text()),
                                                                                    ''.join(self.lineEdit_20.text()),
                                                                                    ''.join(self.lineEdit_21.text()),
                                                                                    ''.join(self.lineEdit_22.text()),
                                                                                    ''.join(self.lineEdit_23.text()),
                                                                                    ''.join(self.lineEdit_24.text()),
                                                                                    ''.join(self.lineEdit_25.text()),
                                                                                    ''.join(self.lineEdit_26.text()),
                                                                                    ''.join(self.lineEdit_27.text()),
                                                                                    ''.join(self.lineEdit_28.text()),
                                                                                    ''.join(self.lineEdit_29.text()),
                                                                                    ''.join(self.lineEdit_30.text()),
                                                                                    ''.join(self.lineEdit_31.text()),
                                                                                    ''.join(self.lineEdit_32.text()),
                                                                                    ''.join(self.lineEdit_33.text()),
                                                                                    ''.join(self.lineEdit_34.text()),
                                                                                    ''.join(self.lineEdit_35.text()),
                                                                                    ''.join(self.lineEdit_36.text()),
                                                                                    ''.join(self.lineEdit_37.text()),
                                                                                    ''.join(self.lineEdit_38.text()),
                                                                                    ''.join(self.lineEdit_39.text()),
                                                                                    ''.join(self.lineEdit_40.text()),
                                                                                    ''.join(self.lineEdit_41.text()),
                                                                                    ''.join(self.lineEdit_42.text()),
                                                                                    ''.join(self.lineEdit_43.text()),
                                                                                    ''.join(self.lineEdit_44.text()),
                                                                                    ''.join(self.lineEdit_74.text()),
                                                                                    ''.join(self.lineEdit_45.text()),
                                                                                    ''.join(self.lineEdit_46.text()),
                                                                                    ''.join(self.lineEdit_47.text()),
                                                                                    ''.join(self.lineEdit_48.text()),
                                                                                    ''.join(self.lineEdit_49.text())))
        print("Candidate Enrolled Successfully")
        
        
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CandidateEnrollment = QtWidgets.QMainWindow()
    ui = Ui_CandidateEnrollment()
    ui.setupUi1(CandidateEnrollment)
    CandidateEnrollment.show()
    sys.exit(app.exec_())