from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CandidateActivityDetails(object):
    def setupUi(self, CandidateActivityDetails):
        CandidateActivityDetails.setObjectName("CandidateActivityDetails")
        CandidateActivityDetails.resize(800, 487)
        self.pushButton_6 = QtWidgets.QPushButton(CandidateActivityDetails)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 450, 107, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(CandidateActivityDetails)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 450, 107, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(CandidateActivityDetails)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 0, 881, 30))
        self.lineEdit_2.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(CandidateActivityDetails)
        self.label.setGeometry(QtCore.QRect(20, 50, 141, 18))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(CandidateActivityDetails)
        self.line.setGeometry(QtCore.QRect(0, 430, 801, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.dateEdit = QtWidgets.QDateEdit(CandidateActivityDetails)
        self.dateEdit.setGeometry(QtCore.QRect(190, 40, 591, 28))
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit_2 = QtWidgets.QTimeEdit(CandidateActivityDetails)
        self.timeEdit_2.setGeometry(QtCore.QRect(190, 80, 591, 28))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.label_2 = QtWidgets.QLabel(CandidateActivityDetails)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 141, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(CandidateActivityDetails)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 141, 18))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(CandidateActivityDetails)
        self.comboBox.setGeometry(QtCore.QRect(190, 120, 551, 28))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(CandidateActivityDetails)
        self.comboBox_2.setGeometry(QtCore.QRect(190, 160, 511, 28))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(CandidateActivityDetails)
        self.comboBox_3.setGeometry(QtCore.QRect(190, 200, 511, 28))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_4 = QtWidgets.QLabel(CandidateActivityDetails)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 141, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(CandidateActivityDetails)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 141, 18))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(CandidateActivityDetails)
        self.pushButton.setGeometry(QtCore.QRect(750, 120, 31, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(CandidateActivityDetails)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 160, 31, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(CandidateActivityDetails)
        self.pushButton_3.setGeometry(QtCore.QRect(710, 200, 31, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(CandidateActivityDetails)
        self.pushButton_4.setGeometry(QtCore.QRect(750, 200, 31, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_7 = QtWidgets.QPushButton(CandidateActivityDetails)
        self.pushButton_7.setGeometry(QtCore.QRect(750, 160, 31, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.textEdit = QtWidgets.QTextEdit(CandidateActivityDetails)
        self.textEdit.setGeometry(QtCore.QRect(20, 250, 761, 161))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(CandidateActivityDetails)
        QtCore.QMetaObject.connectSlotsByName(CandidateActivityDetails)

    def retranslateUi(self, CandidateActivityDetails):
        _translate = QtCore.QCoreApplication.translate
        CandidateActivityDetails.setWindowTitle(_translate("CandidateActivityDetails", "ProTemp"))
        self.pushButton_6.setText(_translate("CandidateActivityDetails", "Cancel"))
        self.pushButton_5.setText(_translate("CandidateActivityDetails", "Ok"))
        self.lineEdit_2.setText(_translate("CandidateActivityDetails", "Candidate Activity Details"))
        self.label.setText(_translate("CandidateActivityDetails", "Date Occurred At:"))
        self.dateEdit.setDisplayFormat(_translate("CandidateActivityDetails", "dd MMMM yyyy "))
        self.timeEdit_2.setDisplayFormat(_translate("CandidateActivityDetails", "HH:mm"))
        self.label_2.setText(_translate("CandidateActivityDetails", "Time Occurred At:"))
        self.label_3.setText(_translate("CandidateActivityDetails", "Activity Type:"))
        self.label_4.setText(_translate("CandidateActivityDetails", "Client:"))
        self.label_5.setText(_translate("CandidateActivityDetails", "Department:"))
        self.pushButton.setText(_translate("CandidateActivityDetails", "F"))
        self.pushButton_2.setText(_translate("CandidateActivityDetails", "F"))
        self.pushButton_3.setText(_translate("CandidateActivityDetails", "F"))
        self.pushButton_4.setText(_translate("CandidateActivityDetails", "X"))
        self.pushButton_7.setText(_translate("CandidateActivityDetails", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CandidateActivityDetails = QtWidgets.QWidget()
    ui = Ui_CandidateActivityDetails()
    ui.setupUi(CandidateActivityDetails)
    CandidateActivityDetails.show()
    sys.exit(app.exec_())
