#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Prev on Mon November 13 11:55 2019

Last Updated on Mon Febuary 10 11:55 2020

@author: pierreb
"""
from PyQt5 import QtCore, QtGui, QtWidgets, uic
import pymysql
import sys
from PyQt5.uic import loadUiType
from PyQt5.QtWidgets import qApp
from PyQt5.QtCore import Qt, QModelIndex
from PyQt5.QtWidgets import QWidget, QApplication, QVBoxLayout, QPushButton, \
    QTableWidget, QTableWidgetItem, QMessageBox, QHBoxLayout, QLineEdit, QLabel, QGridLayout, QHeaderView
from Qualification_add import Ui_Form
from Client_Contact_Details_v102 import Ui_ClientContactDetails
from Client_Department_Details import Ui_Client_Department_Details


class Ui_ClientDetails(object):


    #GUI Start
    def setupUi(self, ClientDetails):
        ClientDetails.setObjectName("ClientDetails")
        ClientDetails.resize(1404, 857)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/Clients.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ClientDetails.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ClientDetails)
        self.centralwidget.setObjectName("centralwidget")
        self.MainTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTabs.setGeometry(QtCore.QRect(10, 10, 1381, 611))
        self.MainTabs.setObjectName("MainTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, -10, 1131, 581))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.label_1.setObjectName("label_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_1.setGeometry(QtCore.QRect(280, 30, 241, 20))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 201, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 60, 241, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 90, 241, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 151, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(280, 120, 241, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_12.setGeometry(QtCore.QRect(760, 30, 241, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(590, 90, 131, 16))
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(590, 220, 131, 16))
        self.label_18.setObjectName("label_18")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_16.setGeometry(QtCore.QRect(760, 120, 241, 20))
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_17.setGeometry(QtCore.QRect(760, 150, 241, 20))
        self.lineEdit_17.setText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(590, 150, 171, 16))
        self.label_17.setObjectName("label_17")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(590, 60, 141, 16))
        self.label_13.setObjectName("label_13")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(590, 30, 131, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_13.setGeometry(QtCore.QRect(760, 60, 241, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_18.setGeometry(QtCore.QRect(760, 220, 191, 20))
        self.lineEdit_18.setText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(590, 120, 131, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_14.setGeometry(QtCore.QRect(760, 90, 241, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.Address = QtWidgets.QTabWidget(self.groupBox)
        self.Address.setGeometry(QtCore.QRect(570, 240, 461, 201))
        self.Address.setObjectName("Address")
        self.Postal = QtWidgets.QWidget()
        self.Postal.setObjectName("Postal")
        self.label_23 = QtWidgets.QLabel(self.Postal)
        self.label_23.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_23.setObjectName("label_23")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_26.setGeometry(QtCore.QRect(180, 110, 91, 20))
        self.lineEdit_26.setText("")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_27 = QtWidgets.QLabel(self.Postal)
        self.label_27.setGeometry(QtCore.QRect(280, 110, 91, 16))
        self.label_27.setObjectName("label_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_28.setGeometry(QtCore.QRect(180, 140, 251, 20))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_26 = QtWidgets.QLabel(self.Postal)
        self.label_26.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_26.setObjectName("label_26")
        self.label_25 = QtWidgets.QLabel(self.Postal)
        self.label_25.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.label_25.setObjectName("label_25")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_21.setGeometry(QtCore.QRect(180, 20, 41, 20))
        self.lineEdit_21.setText("")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_24.setGeometry(QtCore.QRect(390, 50, 51, 20))
        self.lineEdit_24.setText("")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_22 = QtWidgets.QLabel(self.Postal)
        self.label_22.setGeometry(QtCore.QRect(230, 20, 91, 16))
        self.label_22.setObjectName("label_22")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_27.setGeometry(QtCore.QRect(370, 110, 61, 20))
        self.lineEdit_27.setText("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_25.setGeometry(QtCore.QRect(180, 80, 251, 20))
        self.lineEdit_25.setText("")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_21 = QtWidgets.QLabel(self.Postal)
        self.label_21.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_21.setObjectName("label_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_22.setGeometry(QtCore.QRect(310, 20, 141, 20))
        self.lineEdit_22.setText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_24 = QtWidgets.QLabel(self.Postal)
        self.label_24.setGeometry(QtCore.QRect(230, 50, 151, 16))
        self.label_24.setObjectName("label_24")
        self.label_28 = QtWidgets.QLabel(self.Postal)
        self.label_28.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_28.setObjectName("label_28")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_23.setGeometry(QtCore.QRect(180, 50, 41, 20))
        self.lineEdit_23.setText("")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.Address.addTab(self.Postal, "")
        self.PhysicalAddress = QtWidgets.QWidget()
        self.PhysicalAddress.setObjectName("PhysicalAddress")
        self.label_29 = QtWidgets.QLabel(self.PhysicalAddress)
        self.label_29.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.PhysicalAddress)
        self.label_30.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.PhysicalAddress)
        self.label_31.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_31.setObjectName("label_31")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.PhysicalAddress)
        self.lineEdit_29.setGeometry(QtCore.QRect(180, 140, 241, 20))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_32 = QtWidgets.QLabel(self.PhysicalAddress)
        self.label_32.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.PhysicalAddress)
        self.label_33.setGeometry(QtCore.QRect(230, 20, 91, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.PhysicalAddress)
        self.label_34.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_34.setObjectName("label_34")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.PhysicalAddress)
        self.lineEdit_30.setGeometry(QtCore.QRect(180, 80, 241, 20))
        self.lineEdit_30.setText("")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.PhysicalAddress)
        self.lineEdit_31.setGeometry(QtCore.QRect(180, 20, 41, 20))
        self.lineEdit_31.setText("")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.PhysicalAddress)
        self.lineEdit_32.setGeometry(QtCore.QRect(310, 20, 121, 20))
        self.lineEdit_32.setText("")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.label_35 = QtWidgets.QLabel(self.PhysicalAddress)
        self.label_35.setGeometry(QtCore.QRect(280, 110, 91, 16))
        self.label_35.setObjectName("label_35")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.PhysicalAddress)
        self.lineEdit_33.setGeometry(QtCore.QRect(370, 110, 51, 20))
        self.lineEdit_33.setText("")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.PhysicalAddress)
        self.lineEdit_34.setGeometry(QtCore.QRect(380, 50, 51, 20))
        self.lineEdit_34.setText("")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.PhysicalAddress)
        self.lineEdit_35.setGeometry(QtCore.QRect(180, 110, 91, 20))
        self.lineEdit_35.setText("")
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.PhysicalAddress)
        self.lineEdit_36.setGeometry(QtCore.QRect(180, 50, 41, 20))
        self.lineEdit_36.setText("")
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.label_36 = QtWidgets.QLabel(self.PhysicalAddress)
        self.label_36.setGeometry(QtCore.QRect(230, 50, 151, 16))
        self.label_36.setObjectName("label_36")
        self.Address.addTab(self.PhysicalAddress, "")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 230, 211, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(280, 230, 241, 20))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 141, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(280, 150, 241, 20))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 290, 161, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(280, 260, 241, 20))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 191, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 260, 171, 16))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 320, 231, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(280, 180, 241, 20))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(53, 540, 221, 20))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_57 = QtWidgets.QLabel(self.groupBox)
        self.label_57.setGeometry(QtCore.QRect(10, 350, 271, 16))
        self.label_57.setObjectName("label_57")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(280, 290, 113, 29))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setGeometry(QtCore.QRect(280, 320, 113, 29))
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_8.setGeometry(QtCore.QRect(280, 350, 113, 29))
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(590, 180, 171, 16))
        self.label_19.setObjectName("label_19")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_9.setGeometry(QtCore.QRect(760, 170, 113, 29))
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.label_38 = QtWidgets.QLabel(self.groupBox)
        self.label_38.setGeometry(QtCore.QRect(10, 440, 291, 18))
        self.label_38.setObjectName("label_38")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(970, 210, 31, 34))
        self.pushButton_5.setObjectName("pushButton_5")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 480, 541, 22))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(580, 480, 491, 31))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_39 = QtWidgets.QLabel(self.groupBox)
        self.label_39.setGeometry(QtCore.QRect(600, 510, 361, 18))
        self.label_39.setObjectName("label_39")
        self.label_1.raise_()
        self.lineEdit_1.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.label_4.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_12.raise_()
        self.label_14.raise_()
        self.label_18.raise_()
        self.lineEdit_16.raise_()
        self.lineEdit_17.raise_()
        self.label_17.raise_()
        self.label_13.raise_()
        self.label_12.raise_()
        self.lineEdit_13.raise_()
        self.lineEdit_18.raise_()
        self.label_16.raise_()
        self.lineEdit_14.raise_()
        self.label_8.raise_()
        self.lineEdit_8.raise_()
        self.label_5.raise_()
        self.lineEdit_5.raise_()
        self.label_10.raise_()
        self.lineEdit_9.raise_()
        self.label_6.raise_()
        self.label_9.raise_()
        self.label_11.raise_()
        self.lineEdit_6.raise_()
        self.Address.raise_()
        self.label.raise_()
        self.label_57.raise_()
        self.checkBox_6.raise_()
        self.checkBox_7.raise_()
        self.checkBox_8.raise_()
        self.label_19.raise_()
        self.checkBox_9.raise_()
        self.label_38.raise_()
        self.pushButton_5.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.label_39.raise_()
        self.MainTabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_13.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_12.setObjectName("pushButton_12")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.MainTabs.addTab(self.tab_2, "")
        self.tabDepartments = QtWidgets.QWidget()
        self.tabDepartments.setObjectName("tabDepartments")
        self.pushButton_7 = QtWidgets.QPushButton(self.tabDepartments)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tabDepartments)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tableWidget = QtWidgets.QTableWidget(self.tabDepartments)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.MainTabs.addTab(self.tabDepartments, "")
        self.tabUnpreferdCandidates = QtWidgets.QWidget()
        self.tabUnpreferdCandidates.setObjectName("tabUnpreferdCandidates")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tabUnpreferdCandidates)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 60, 751, 121))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(1)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        self.pushButton_15 = QtWidgets.QPushButton(self.tabUnpreferdCandidates)
        self.pushButton_15.setGeometry(QtCore.QRect(0, 10, 87, 29))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tabUnpreferdCandidates)
        self.pushButton_16.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_16.setObjectName("pushButton_16")
        self.MainTabs.addTab(self.tabUnpreferdCandidates, "")
        self.TabLinkedUsers = QtWidgets.QWidget()
        self.TabLinkedUsers.setObjectName("TabLinkedUsers")
        self.pushButton_17 = QtWidgets.QPushButton(self.TabLinkedUsers)
        self.pushButton_17.setGeometry(QtCore.QRect(90, 10, 87, 29))
        self.pushButton_17.setObjectName("pushButton_17")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.TabLinkedUsers)
        self.tableWidget_7.setGeometry(QtCore.QRect(0, 60, 751, 121))
        self.tableWidget_7.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(1)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        self.pushButton_18 = QtWidgets.QPushButton(self.TabLinkedUsers)
        self.pushButton_18.setGeometry(QtCore.QRect(0, 10, 87, 29))
        self.pushButton_18.setObjectName("pushButton_18")
        self.MainTabs.addTab(self.TabLinkedUsers, "")
        self.TabUserDefinedFields = QtWidgets.QWidget()
        self.TabUserDefinedFields.setObjectName("TabUserDefinedFields")
        self.pushButton_20 = QtWidgets.QPushButton(self.TabUserDefinedFields)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 10, 131, 29))
        self.pushButton_20.setObjectName("pushButton_20")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.TabUserDefinedFields)
        self.tableWidget_8.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget_8.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(1)
        self.tableWidget_8.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        self.MainTabs.addTab(self.TabUserDefinedFields, "")
        self.TabActivities = QtWidgets.QWidget()
        self.TabActivities.setObjectName("TabActivities")
        self.pushButton_27 = QtWidgets.QPushButton(self.TabActivities)
        self.pushButton_27.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.TabActivities)
        self.pushButton_28.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.TabActivities)
        self.pushButton_29.setGeometry(QtCore.QRect(190, 10, 87, 29))
        self.pushButton_29.setObjectName("pushButton_29")
        self.tableWidget_10 = QtWidgets.QTableWidget(self.TabActivities)
        self.tableWidget_10.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget_10.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(3)
        self.tableWidget_10.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(2, item)
        self.MainTabs.addTab(self.TabActivities, "")
        self.TabAdministration = QtWidgets.QWidget()
        self.TabAdministration.setObjectName("TabAdministration")
        self.label_160 = QtWidgets.QLabel(self.TabAdministration)
        self.label_160.setGeometry(QtCore.QRect(10, 40, 161, 17))
        self.label_160.setObjectName("label_160")
        self.label_161 = QtWidgets.QLabel(self.TabAdministration)
        self.label_161.setGeometry(QtCore.QRect(10, 100, 161, 17))
        self.label_161.setObjectName("label_161")
        self.label_162 = QtWidgets.QLabel(self.TabAdministration)
        self.label_162.setGeometry(QtCore.QRect(10, 70, 171, 17))
        self.label_162.setObjectName("label_162")
        self.label_164 = QtWidgets.QLabel(self.TabAdministration)
        self.label_164.setGeometry(QtCore.QRect(10, 10, 181, 17))
        self.label_164.setObjectName("label_164")
        self.lineEdit_133 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_133.setGeometry(QtCore.QRect(240, 40, 221, 21))
        self.lineEdit_133.setObjectName("lineEdit_133")
        self.lineEdit_138 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_138.setGeometry(QtCore.QRect(240, 70, 221, 21))
        self.lineEdit_138.setObjectName("lineEdit_138")
        self.lineEdit_139 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_139.setGeometry(QtCore.QRect(240, 10, 221, 21))
        self.lineEdit_139.setObjectName("lineEdit_139")
        self.lineEdit_140 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_140.setGeometry(QtCore.QRect(240, 100, 221, 21))
        self.lineEdit_140.setObjectName("lineEdit_140")
        self.MainTabs.addTab(self.TabAdministration, "")
        self.TabAttachments = QtWidgets.QWidget()
        self.TabAttachments.setObjectName("TabAttachments")
        self.pushButton_30 = QtWidgets.QPushButton(self.TabAttachments)
        self.pushButton_30.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.TabAttachments)
        self.pushButton_31.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.TabAttachments)
        self.pushButton_32.setGeometry(QtCore.QRect(190, 10, 87, 29))
        self.pushButton_32.setObjectName("pushButton_32")
        self.tableWidget_11 = QtWidgets.QTableWidget(self.TabAttachments)
        self.tableWidget_11.setGeometry(QtCore.QRect(10, 90, 751, 121))
        self.tableWidget_11.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_11.setObjectName("tableWidget_11")
        self.tableWidget_11.setColumnCount(3)
        self.tableWidget_11.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_11.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_11.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_11.setHorizontalHeaderItem(2, item)
        self.pushButton_33 = QtWidgets.QPushButton(self.TabAttachments)
        self.pushButton_33.setGeometry(QtCore.QRect(280, 10, 87, 29))
        self.pushButton_33.setObjectName("pushButton_33")
        self.lineEdit = QtWidgets.QLineEdit(self.TabAttachments)
        self.lineEdit.setGeometry(QtCore.QRect(20, 50, 171, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.MainTabs.addTab(self.TabAttachments, "")
        self.TabRates = QtWidgets.QWidget()
        self.TabRates.setObjectName("TabRates")
        self.label_7 = QtWidgets.QLabel(self.TabRates)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 141, 18))
        self.label_7.setObjectName("label_7")
        self.label_15 = QtWidgets.QLabel(self.TabRates)
        self.label_15.setGeometry(QtCore.QRect(10, 50, 131, 18))
        self.label_15.setObjectName("label_15")
        self.label_20 = QtWidgets.QLabel(self.TabRates)
        self.label_20.setGeometry(QtCore.QRect(570, 10, 91, 18))
        self.label_20.setObjectName("label_20")
        self.label_37 = QtWidgets.QLabel(self.TabRates)
        self.label_37.setGeometry(QtCore.QRect(570, 50, 91, 18))
        self.label_37.setObjectName("label_37")
        self.pushButton_3 = QtWidgets.QPushButton(self.TabRates)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 0, 31, 34))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.TabRates)
        self.pushButton_4.setGeometry(QtCore.QRect(500, 40, 31, 34))
        self.pushButton_4.setObjectName("pushButton_4")
        self.dateEdit = QtWidgets.QDateEdit(self.TabRates)
        self.dateEdit.setGeometry(QtCore.QRect(710, 0, 125, 32))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.TabRates)
        self.dateEdit_2.setGeometry(QtCore.QRect(710, 40, 125, 32))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.TabRates)
        self.lineEdit_7.setGeometry(QtCore.QRect(150, 0, 341, 32))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.TabRates)
        self.lineEdit_10.setGeometry(QtCore.QRect(150, 40, 341, 32))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.MainTabs.addTab(self.TabRates, "")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 630, 721, 81))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 730, 781, 41))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 777, 37))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 10, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(830, 660, 107, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(950, 660, 107, 30))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(830, 710, 107, 30))
        self.pushButton_11.setObjectName("pushButton_11")
        ClientDetails.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ClientDetails)
        self.statusbar.setObjectName("statusbar")
        ClientDetails.setStatusBar(self.statusbar)
        #GUI End


        self.pushButton.clicked.connect(self.InsertData)
        self.pushButton_12.clicked.connect(self.openWindow1)
        self.pushButton_7.clicked.connect(self.openWindow2)


        self.retranslateUi(ClientDetails)
        self.MainTabs.setCurrentIndex(0)
        self.Address.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ClientDetails)


    def openWindow1(self):
        self.window = QtWidgets.QMainWindow()
        self.ui1 = Ui_ClientContactDetails()
        self.ui1.setupUi(self.window)
        self.window.show()


    def openWindow2(self):
        self.window = QtWidgets.QMainWindow()
        self.ui2 = Ui_Client_Department_Details()
        self.ui2.setupUi(self.window)
        self.window.show()


    #GUI Start
    def retranslateUi(self, ClientDetails):
        _translate = QtCore.QCoreApplication.translate
        ClientDetails.setWindowTitle(_translate("ClientDetails", "Client Details"))
        self.label_1.setText(_translate("ClientDetails", "Company Name:"))
        self.label_2.setText(_translate("ClientDetails", "VAT Registraion Number:"))
        self.label_3.setText(_translate("ClientDetails", "Payroll Code:"))
        self.label_4.setText(_translate("ClientDetails", "Integration Code:"))
        self.label_14.setText(_translate("ClientDetails", "Telephone Fax:"))
        self.label_18.setText(_translate("ClientDetails", "Category:"))
        self.label_17.setText(_translate("ClientDetails", "Invoice Template:"))
        self.label_13.setText(_translate("ClientDetails", "Telephone Work:"))
        self.label_12.setText(_translate("ClientDetails", "Folder (Status):"))
        self.label_16.setText(_translate("ClientDetails", "Email Address:"))
        self.label_23.setText(_translate("ClientDetails", "Street Nr:"))
        self.label_27.setText(_translate("ClientDetails", "Postal Code:"))
        self.lineEdit_28.setText(_translate("ClientDetails", "South Africa"))
        self.label_26.setText(_translate("ClientDetails", "City/Town:"))
        self.label_25.setText(_translate("ClientDetails", "Suburb/District:"))
        self.label_22.setText(_translate("ClientDetails", "Complex:"))
        self.label_21.setText(_translate("ClientDetails", "Unit Nr:"))
        self.label_24.setText(_translate("ClientDetails", "Street Name/Farm:"))
        self.label_28.setText(_translate("ClientDetails", "Country/Region:"))
        self.Address.setTabText(self.Address.indexOf(self.Postal), _translate("ClientDetails", "Postal"))
        self.label_29.setText(_translate("ClientDetails", "Suburb/District:"))
        self.label_30.setText(_translate("ClientDetails", "City/Town:"))
        self.label_31.setText(_translate("ClientDetails", "Country/Region:"))
        self.lineEdit_29.setText(_translate("ClientDetails", "South Africa"))
        self.label_32.setText(_translate("ClientDetails", "Unit Nr:"))
        self.label_33.setText(_translate("ClientDetails", "Complex:"))
        self.label_34.setText(_translate("ClientDetails", "Street Nr:"))
        self.label_35.setText(_translate("ClientDetails", "Postal Code:"))
        self.label_36.setText(_translate("ClientDetails", "Street Name/Farm:"))
        self.Address.setTabText(self.Address.indexOf(self.PhysicalAddress), _translate("ClientDetails", "Physical Address"))
        self.label_8.setText(_translate("ClientDetails", "Financial Account Number:"))
        self.label_5.setText(_translate("ClientDetails", "Paying Hours:"))
        self.label_10.setText(_translate("ClientDetails", "Is VAT Payable:"))
        self.label_6.setText(_translate("ClientDetails", "Days Between Payments:"))
        self.label_9.setText(_translate("ClientDetails", "Sales Ledger:"))
        self.label_11.setText(_translate("ClientDetails", "Split Invoice By Department:"))
        self.label_57.setText(_translate("ClientDetails", "Allow Zero Values On Timesheets:"))
        self.label_19.setText(_translate("ClientDetails", "Is Paying Leave:"))
        self.label_38.setText(_translate("ClientDetails", "<html><head/><body><p><span style=\" color:#0000ff;\">Public Holiday Shift</span></p></body></html>"))
        self.pushButton_5.setText(_translate("ClientDetails", "X"))
        self.radioButton.setText(_translate("ClientDetails", "The night shift on a public holiday is classed as public holiday night."))
        self.radioButton_2.setText(_translate("ClientDetails", "The night shift on a public holiday is classed as normal night"))
        self.label_39.setText(_translate("ClientDetails", " and the night before as public holiday night."))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab), _translate("ClientDetails", "General"))
        self.pushButton_13.setText(_translate("ClientDetails", "Delete"))
        self.pushButton_12.setText(_translate("ClientDetails", "Add"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "Code"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("ClientDetails", "Description        "))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab_2), _translate("ClientDetails", "Contacts"))
        self.pushButton_7.setText(_translate("ClientDetails", "Add"))
        self.pushButton_8.setText(_translate("ClientDetails", "Delete"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "Code"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ClientDetails", "Description        "))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tabDepartments), _translate("ClientDetails", "Departments"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "Candidate"))
        self.pushButton_15.setText(_translate("ClientDetails", "Add"))
        self.pushButton_16.setText(_translate("ClientDetails", "Delete"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tabUnpreferdCandidates), _translate("ClientDetails", "Unprefered Candidates"))
        self.pushButton_17.setText(_translate("ClientDetails", "Delete"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "User"))
        self.pushButton_18.setText(_translate("ClientDetails", "Add"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabLinkedUsers), _translate("ClientDetails", "Linked Users"))
        self.pushButton_20.setText(_translate("ClientDetails", "New Field..."))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "Description"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabUserDefinedFields), _translate("ClientDetails", "User-Defined Fields"))
        self.pushButton_27.setText(_translate("ClientDetails", "Update"))
        self.pushButton_28.setText(_translate("ClientDetails", "Add"))
        self.pushButton_29.setText(_translate("ClientDetails", "Delete"))
        item = self.tableWidget_10.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "Occurred At"))
        item = self.tableWidget_10.horizontalHeaderItem(1)
        item.setText(_translate("ClientDetails", "Activity Type"))
        item = self.tableWidget_10.horizontalHeaderItem(2)
        item.setText(_translate("ClientDetails", "User"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabActivities), _translate("ClientDetails", "Activities"))
        self.label_160.setText(_translate("ClientDetails", "Created On:"))
        self.label_161.setText(_translate("ClientDetails", "Last Updated On:"))
        self.label_162.setText(_translate("ClientDetails", "Last Updated By:"))
        self.label_164.setText(_translate("ClientDetails", "Created By:"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabAdministration), _translate("ClientDetails", "Administration"))
        self.pushButton_30.setText(_translate("ClientDetails", "Update"))
        self.pushButton_31.setText(_translate("ClientDetails", "Add"))
        self.pushButton_32.setText(_translate("ClientDetails", "Delete"))
        item = self.tableWidget_11.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "NodifiedDate"))
        item = self.tableWidget_11.horizontalHeaderItem(1)
        item.setText(_translate("ClientDetails", "Descrition"))
        item = self.tableWidget_11.horizontalHeaderItem(2)
        item.setText(_translate("ClientDetails", "FileName"))
        self.pushButton_33.setText(_translate("ClientDetails", "Open"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabAttachments), _translate("ClientDetails", "Attachments"))
        self.label_7.setText(_translate("ClientDetails", "Rate Template 1:"))
        self.label_15.setText(_translate("ClientDetails", "Rate Template 2:"))
        self.label_20.setText(_translate("ClientDetails", "> Expires:"))
        self.label_37.setText(_translate("ClientDetails", "> Expires:"))
        self.pushButton_3.setText(_translate("ClientDetails", "X"))
        self.pushButton_4.setText(_translate("ClientDetails", "X"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabRates), _translate("ClientDetails", "Rates"))
        self.pushButton.setText(_translate("ClientDetails", "Ok"))
        self.pushButton_2.setText(_translate("ClientDetails", "Cancel"))
        self.pushButton_9.setText(_translate("ClientDetails", "Theme1"))
        self.pushButton_10.setText(_translate("ClientDetails", "Theme2"))
        self.pushButton_11.setText(_translate("ClientDetails", "Theme3"))
        #GUI End


    def InsertData(self):
        con = pymysql.connect(host='localhost',
                             user='root',
                             password='',                             
                             db='medx',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
        with con:
                cur = con.cursor()
                cur.execute("INSERT INTO client2(CompanyName, VATRegistrationNumber, PayrollCode, IntegrationCode, PayingHoursID, NumberOfDaysBetweenPayment, FinancialAccountNumber, SalesLedger, IsVatPayable, ClientFolderID, TelephoneWork, TelephoneFax, EmailAddress, DocumentTemplateID)"
                            "VALUES('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s')" %(''.join(self.lineEdit_1.text()),
                                                                                    ''.join(self.lineEdit_2.text()),
                                                                                    ''.join(self.lineEdit_3.text()),
                                                                                    ''.join(self.lineEdit_4.text()),
                                                                                    ''.join(self.lineEdit_5.text()),
                                                                                    ''.join(self.lineEdit_6.text()),
                                                                                    ''.join(self.lineEdit_8.text()),
                                                                                    ''.join(self.lineEdit_9.text()),
                                                                                    ''.join(self.lineEdit_18.text()),
                                                                                    ''.join(self.lineEdit_12.text()),
                                                                                    ''.join(self.lineEdit_13.text()),
                                                                                    ''.join(self.lineEdit_14.text()),
                                                                                    ''.join(self.lineEdit_16.text()),
                                                                                    ''.join(self.lineEdit_17.text())))                                                                                    
        print("Client Enrolled Successfully")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClientDetails = QtWidgets.QMainWindow()
    ui = Ui_ClientDetails()
    ui.setupUi(ClientDetails)
    ClientDetails.show()
    sys.exit(app.exec_())

