from PyQt5 import QtCore, QtGui, QtWidgets, uic
import pymysql
import sys
from PyQt5.uic import loadUiType
from PyQt5.QtWidgets import qApp
from PyQt5.QtCore import Qt, QModelIndex
from PyQt5.QtWidgets import QWidget, QApplication, QVBoxLayout, QPushButton, \
    QTableWidget, QTableWidgetItem, QMessageBox, QHBoxLayout, QLineEdit, QLabel, QGridLayout, QHeaderView
from Qualification_add import Ui_Form
from Client_Contact_Details_v102 import Ui_ClientContactDetails


class Ui_ClientDetailsUpdate(object):
    def setupUi(self, ClientDetails):
        ClientDetails.setObjectName("ClientDetails")
        ClientDetails.resize(1404, 834)
        self.centralwidget = QtWidgets.QWidget(ClientDetails)
        self.centralwidget.setObjectName("centralwidget")
        self.MainTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTabs.setGeometry(QtCore.QRect(10, 10, 1381, 611))
        self.MainTabs.setObjectName("MainTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, -10, 1031, 651))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.label_1.setObjectName("label_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_1.setGeometry(QtCore.QRect(280, 30, 241, 20))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 201, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 60, 241, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 90, 241, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 151, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(280, 120, 241, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_12.setGeometry(QtCore.QRect(760, 30, 241, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(590, 90, 131, 16))
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(590, 270, 131, 16))
        self.label_18.setObjectName("label_18")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_16.setGeometry(QtCore.QRect(760, 120, 241, 20))
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_17.setGeometry(QtCore.QRect(760, 150, 241, 20))
        self.lineEdit_17.setText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(590, 150, 171, 16))
        self.label_17.setObjectName("label_17")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(590, 60, 141, 16))
        self.label_13.setObjectName("label_13")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(590, 30, 131, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_13.setGeometry(QtCore.QRect(760, 60, 241, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_18.setGeometry(QtCore.QRect(760, 270, 241, 20))
        self.lineEdit_18.setText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(590, 120, 131, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_14.setGeometry(QtCore.QRect(760, 90, 241, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.Address = QtWidgets.QTabWidget(self.groupBox)
        self.Address.setGeometry(QtCore.QRect(570, 300, 531, 301))
        self.Address.setObjectName("Address")
        self.Phyical = QtWidgets.QWidget()
        self.Phyical.setObjectName("Phyical")
        self.label_23 = QtWidgets.QLabel(self.Phyical)
        self.label_23.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_23.setObjectName("label_23")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_26.setGeometry(QtCore.QRect(180, 110, 91, 20))
        self.lineEdit_26.setText("")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_27 = QtWidgets.QLabel(self.Phyical)
        self.label_27.setGeometry(QtCore.QRect(280, 110, 91, 16))
        self.label_27.setObjectName("label_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_28.setGeometry(QtCore.QRect(180, 140, 251, 20))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_26 = QtWidgets.QLabel(self.Phyical)
        self.label_26.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_26.setObjectName("label_26")
        self.label_25 = QtWidgets.QLabel(self.Phyical)
        self.label_25.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.label_25.setObjectName("label_25")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_21.setGeometry(QtCore.QRect(180, 20, 41, 20))
        self.lineEdit_21.setText("")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_24.setGeometry(QtCore.QRect(390, 50, 51, 20))
        self.lineEdit_24.setText("")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_22 = QtWidgets.QLabel(self.Phyical)
        self.label_22.setGeometry(QtCore.QRect(230, 20, 91, 16))
        self.label_22.setObjectName("label_22")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_27.setGeometry(QtCore.QRect(370, 110, 61, 20))
        self.lineEdit_27.setText("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_25.setGeometry(QtCore.QRect(180, 80, 251, 20))
        self.lineEdit_25.setText("")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_21 = QtWidgets.QLabel(self.Phyical)
        self.label_21.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_21.setObjectName("label_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_22.setGeometry(QtCore.QRect(310, 20, 141, 20))
        self.lineEdit_22.setText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_24 = QtWidgets.QLabel(self.Phyical)
        self.label_24.setGeometry(QtCore.QRect(230, 50, 151, 16))
        self.label_24.setObjectName("label_24")
        self.label_28 = QtWidgets.QLabel(self.Phyical)
        self.label_28.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_28.setObjectName("label_28")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.Phyical)
        self.lineEdit_23.setGeometry(QtCore.QRect(180, 50, 41, 20))
        self.lineEdit_23.setText("")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.Address.addTab(self.Phyical, "")
        self.Postal = QtWidgets.QWidget()
        self.Postal.setObjectName("Postal")
        self.label_29 = QtWidgets.QLabel(self.Postal)
        self.label_29.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.Postal)
        self.label_30.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.Postal)
        self.label_31.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_31.setObjectName("label_31")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_29.setGeometry(QtCore.QRect(180, 140, 241, 20))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_32 = QtWidgets.QLabel(self.Postal)
        self.label_32.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.Postal)
        self.label_33.setGeometry(QtCore.QRect(230, 20, 91, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.Postal)
        self.label_34.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_34.setObjectName("label_34")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_30.setGeometry(QtCore.QRect(180, 80, 241, 20))
        self.lineEdit_30.setText("")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_31.setGeometry(QtCore.QRect(180, 20, 41, 20))
        self.lineEdit_31.setText("")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_32.setGeometry(QtCore.QRect(310, 20, 121, 20))
        self.lineEdit_32.setText("")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.label_35 = QtWidgets.QLabel(self.Postal)
        self.label_35.setGeometry(QtCore.QRect(280, 110, 91, 16))
        self.label_35.setObjectName("label_35")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_33.setGeometry(QtCore.QRect(370, 110, 51, 20))
        self.lineEdit_33.setText("")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_34.setGeometry(QtCore.QRect(380, 50, 51, 20))
        self.lineEdit_34.setText("")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_35.setGeometry(QtCore.QRect(180, 110, 91, 20))
        self.lineEdit_35.setText("")
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.Postal)
        self.lineEdit_36.setGeometry(QtCore.QRect(180, 50, 41, 20))
        self.lineEdit_36.setText("")
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.label_36 = QtWidgets.QLabel(self.Postal)
        self.label_36.setGeometry(QtCore.QRect(230, 50, 151, 16))
        self.label_36.setObjectName("label_36")
        self.Address.addTab(self.Postal, "")
        self.Work = QtWidgets.QWidget()
        self.Work.setObjectName("Work")
        self.label_37 = QtWidgets.QLabel(self.Work)
        self.label_37.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.Work)
        self.label_38.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.Work)
        self.label_39.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_39.setObjectName("label_39")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_37.setGeometry(QtCore.QRect(180, 140, 241, 20))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.label_40 = QtWidgets.QLabel(self.Work)
        self.label_40.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.Work)
        self.label_41.setGeometry(QtCore.QRect(230, 20, 91, 16))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.Work)
        self.label_42.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_42.setObjectName("label_42")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_38.setGeometry(QtCore.QRect(180, 80, 241, 20))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_39.setGeometry(QtCore.QRect(180, 20, 41, 20))
        self.lineEdit_39.setText("")
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_40.setGeometry(QtCore.QRect(310, 20, 121, 20))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.label_43 = QtWidgets.QLabel(self.Work)
        self.label_43.setGeometry(QtCore.QRect(280, 110, 91, 16))
        self.label_43.setObjectName("label_43")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_41.setGeometry(QtCore.QRect(370, 110, 51, 20))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_42.setGeometry(QtCore.QRect(340, 50, 101, 20))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_43.setGeometry(QtCore.QRect(180, 110, 91, 20))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.Work)
        self.lineEdit_44.setGeometry(QtCore.QRect(180, 50, 41, 20))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.label_44 = QtWidgets.QLabel(self.Work)
        self.label_44.setGeometry(QtCore.QRect(230, 50, 151, 16))
        self.label_44.setObjectName("label_44")
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.lineEdit_37.raise_()
        self.label_40.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.lineEdit_38.raise_()
        self.lineEdit_39.raise_()
        self.lineEdit_40.raise_()
        self.label_43.raise_()
        self.lineEdit_41.raise_()
        self.lineEdit_43.raise_()
        self.lineEdit_44.raise_()
        self.label_44.raise_()
        self.lineEdit_42.raise_()
        self.Address.addTab(self.Work, "")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 230, 211, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(280, 230, 241, 20))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 141, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(280, 150, 241, 20))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 290, 161, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(280, 260, 241, 20))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 191, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 260, 171, 16))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 320, 231, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(280, 180, 241, 20))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(53, 540, 221, 20))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_57 = QtWidgets.QLabel(self.groupBox)
        self.label_57.setGeometry(QtCore.QRect(10, 350, 271, 16))
        self.label_57.setObjectName("label_57")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(280, 290, 113, 29))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setGeometry(QtCore.QRect(280, 320, 113, 29))
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_8.setGeometry(QtCore.QRect(280, 350, 113, 29))
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(590, 180, 171, 16))
        self.label_19.setObjectName("label_19")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_9.setGeometry(QtCore.QRect(760, 170, 113, 29))
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.label_1.raise_()
        self.lineEdit_1.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.label_4.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_12.raise_()
        self.label_14.raise_()
        self.label_18.raise_()
        self.lineEdit_16.raise_()
        self.lineEdit_17.raise_()
        self.label_17.raise_()
        self.label_13.raise_()
        self.label_12.raise_()
        self.lineEdit_13.raise_()
        self.lineEdit_18.raise_()
        self.label_16.raise_()
        self.lineEdit_14.raise_()
        self.label_8.raise_()
        self.lineEdit_8.raise_()
        self.label_5.raise_()
        self.lineEdit_5.raise_()
        self.label_10.raise_()
        self.lineEdit_9.raise_()
        self.label_6.raise_()
        self.label_9.raise_()
        self.label_11.raise_()
        self.lineEdit_6.raise_()
        self.Address.raise_()
        self.label.raise_()
        self.label_57.raise_()
        self.checkBox_6.raise_()
        self.checkBox_7.raise_()
        self.checkBox_8.raise_()
        self.label_19.raise_()
        self.checkBox_9.raise_()
        self.MainTabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_13.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_12.setObjectName("pushButton_12")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.MainTabs.addTab(self.tab_2, "")
        self.tabDepartments = QtWidgets.QWidget()
        self.tabDepartments.setObjectName("tabDepartments")
        self.pushButton_7 = QtWidgets.QPushButton(self.tabDepartments)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tabDepartments)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tableWidget = QtWidgets.QTableWidget(self.tabDepartments)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.MainTabs.addTab(self.tabDepartments, "")
        self.tabUnpreferdCandidates = QtWidgets.QWidget()
        self.tabUnpreferdCandidates.setObjectName("tabUnpreferdCandidates")
        self.pushButton_14 = QtWidgets.QPushButton(self.tabUnpreferdCandidates)
        self.pushButton_14.setGeometry(QtCore.QRect(90, 10, 87, 29))
        self.pushButton_14.setObjectName("pushButton_14")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tabUnpreferdCandidates)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 60, 751, 121))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(3)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        self.pushButton_15 = QtWidgets.QPushButton(self.tabUnpreferdCandidates)
        self.pushButton_15.setGeometry(QtCore.QRect(0, 10, 87, 29))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tabUnpreferdCandidates)
        self.pushButton_16.setGeometry(QtCore.QRect(180, 10, 87, 29))
        self.pushButton_16.setObjectName("pushButton_16")
        self.MainTabs.addTab(self.tabUnpreferdCandidates, "")
        self.TabLinkedUsers = QtWidgets.QWidget()
        self.TabLinkedUsers.setObjectName("TabLinkedUsers")
        self.pushButton_17 = QtWidgets.QPushButton(self.TabLinkedUsers)
        self.pushButton_17.setGeometry(QtCore.QRect(180, 10, 87, 29))
        self.pushButton_17.setObjectName("pushButton_17")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.TabLinkedUsers)
        self.tableWidget_7.setGeometry(QtCore.QRect(0, 60, 751, 121))
        self.tableWidget_7.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(3)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        self.pushButton_18 = QtWidgets.QPushButton(self.TabLinkedUsers)
        self.pushButton_18.setGeometry(QtCore.QRect(0, 10, 87, 29))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.TabLinkedUsers)
        self.pushButton_19.setGeometry(QtCore.QRect(90, 10, 87, 29))
        self.pushButton_19.setObjectName("pushButton_19")
        self.MainTabs.addTab(self.TabLinkedUsers, "")
        self.TabUserDefinedFields = QtWidgets.QWidget()
        self.TabUserDefinedFields.setObjectName("TabUserDefinedFields")
        self.pushButton_20 = QtWidgets.QPushButton(self.TabUserDefinedFields)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.TabUserDefinedFields)
        self.pushButton_21.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.TabUserDefinedFields)
        self.pushButton_22.setGeometry(QtCore.QRect(190, 10, 87, 29))
        self.pushButton_22.setObjectName("pushButton_22")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.TabUserDefinedFields)
        self.tableWidget_8.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget_8.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(3)
        self.tableWidget_8.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_8.setHorizontalHeaderItem(2, item)
        self.MainTabs.addTab(self.TabUserDefinedFields, "")
        self.TabLinkedClients = QtWidgets.QWidget()
        self.TabLinkedClients.setObjectName("TabLinkedClients")
        self.pushButton_23 = QtWidgets.QPushButton(self.TabLinkedClients)
        self.pushButton_23.setGeometry(QtCore.QRect(0, 0, 87, 29))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.TabLinkedClients)
        self.pushButton_24.setGeometry(QtCore.QRect(90, 0, 87, 29))
        self.pushButton_24.setObjectName("pushButton_24")
        self.tableWidget_9 = QtWidgets.QTableWidget(self.TabLinkedClients)
        self.tableWidget_9.setGeometry(QtCore.QRect(0, 50, 751, 121))
        self.tableWidget_9.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(3)
        self.tableWidget_9.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        self.pushButton_25 = QtWidgets.QPushButton(self.TabLinkedClients)
        self.pushButton_25.setGeometry(QtCore.QRect(180, 0, 87, 29))
        self.pushButton_25.setObjectName("pushButton_25")
        self.MainTabs.addTab(self.TabLinkedClients, "")
        self.TabUserDefinedFields1 = QtWidgets.QWidget()
        self.TabUserDefinedFields1.setObjectName("TabUserDefinedFields1")
        self.label_149 = QtWidgets.QLabel(self.TabUserDefinedFields1)
        self.label_149.setGeometry(QtCore.QRect(10, 160, 161, 17))
        self.label_149.setObjectName("label_149")
        self.lineEdit_131 = QtWidgets.QLineEdit(self.TabUserDefinedFields1)
        self.lineEdit_131.setGeometry(QtCore.QRect(230, 100, 741, 21))
        self.lineEdit_131.setObjectName("lineEdit_131")
        self.lineEdit_132 = QtWidgets.QLineEdit(self.TabUserDefinedFields1)
        self.lineEdit_132.setGeometry(QtCore.QRect(230, 130, 741, 21))
        self.lineEdit_132.setObjectName("lineEdit_132")
        self.label_150 = QtWidgets.QLabel(self.TabUserDefinedFields1)
        self.label_150.setGeometry(QtCore.QRect(10, 100, 161, 17))
        self.label_150.setObjectName("label_150")
        self.lineEdit_134 = QtWidgets.QLineEdit(self.TabUserDefinedFields1)
        self.lineEdit_134.setGeometry(QtCore.QRect(230, 220, 741, 21))
        self.lineEdit_134.setObjectName("lineEdit_134")
        self.lineEdit_135 = QtWidgets.QLineEdit(self.TabUserDefinedFields1)
        self.lineEdit_135.setGeometry(QtCore.QRect(230, 70, 741, 21))
        self.lineEdit_135.setObjectName("lineEdit_135")
        self.lineEdit_136 = QtWidgets.QLineEdit(self.TabUserDefinedFields1)
        self.lineEdit_136.setGeometry(QtCore.QRect(230, 160, 741, 21))
        self.lineEdit_136.setObjectName("lineEdit_136")
        self.label_151 = QtWidgets.QLabel(self.TabUserDefinedFields1)
        self.label_151.setGeometry(QtCore.QRect(10, 190, 171, 17))
        self.label_151.setObjectName("label_151")
        self.label_152 = QtWidgets.QLabel(self.TabUserDefinedFields1)
        self.label_152.setGeometry(QtCore.QRect(10, 250, 221, 17))
        self.label_152.setObjectName("label_152")
        self.lineEdit_137 = QtWidgets.QLineEdit(self.TabUserDefinedFields1)
        self.lineEdit_137.setGeometry(QtCore.QRect(230, 190, 741, 21))
        self.lineEdit_137.setObjectName("lineEdit_137")
        self.label_153 = QtWidgets.QLabel(self.TabUserDefinedFields1)
        self.label_153.setGeometry(QtCore.QRect(10, 130, 171, 17))
        self.label_153.setObjectName("label_153")
        self.label_154 = QtWidgets.QLabel(self.TabUserDefinedFields1)
        self.label_154.setGeometry(QtCore.QRect(10, 220, 181, 17))
        self.label_154.setObjectName("label_154")
        self.label_155 = QtWidgets.QLabel(self.TabUserDefinedFields1)
        self.label_155.setGeometry(QtCore.QRect(10, 70, 181, 17))
        self.label_155.setObjectName("label_155")
        self.pushButton_26 = QtWidgets.QPushButton(self.TabUserDefinedFields1)
        self.pushButton_26.setGeometry(QtCore.QRect(10, 10, 121, 29))
        self.pushButton_26.setObjectName("pushButton_26")
        self.checkBox = QtWidgets.QCheckBox(self.TabUserDefinedFields1)
        self.checkBox.setGeometry(QtCore.QRect(340, 250, 113, 29))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.TabUserDefinedFields1)
        self.checkBox_2.setGeometry(QtCore.QRect(340, 280, 113, 29))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.TabUserDefinedFields1)
        self.checkBox_3.setGeometry(QtCore.QRect(340, 310, 113, 29))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.TabUserDefinedFields1)
        self.checkBox_4.setGeometry(QtCore.QRect(340, 340, 113, 29))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.TabUserDefinedFields1)
        self.checkBox_5.setGeometry(QtCore.QRect(340, 370, 113, 29))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_156 = QtWidgets.QLabel(self.TabUserDefinedFields1)
        self.label_156.setGeometry(QtCore.QRect(10, 310, 321, 17))
        self.label_156.setObjectName("label_156")
        self.label_157 = QtWidgets.QLabel(self.TabUserDefinedFields1)
        self.label_157.setGeometry(QtCore.QRect(10, 340, 221, 17))
        self.label_157.setObjectName("label_157")
        self.label_158 = QtWidgets.QLabel(self.TabUserDefinedFields1)
        self.label_158.setGeometry(QtCore.QRect(10, 370, 221, 17))
        self.label_158.setObjectName("label_158")
        self.label_159 = QtWidgets.QLabel(self.TabUserDefinedFields1)
        self.label_159.setGeometry(QtCore.QRect(10, 280, 321, 17))
        self.label_159.setObjectName("label_159")
        self.MainTabs.addTab(self.TabUserDefinedFields1, "")
        self.TabActivities = QtWidgets.QWidget()
        self.TabActivities.setObjectName("TabActivities")
        self.pushButton_27 = QtWidgets.QPushButton(self.TabActivities)
        self.pushButton_27.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.TabActivities)
        self.pushButton_28.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.TabActivities)
        self.pushButton_29.setGeometry(QtCore.QRect(190, 10, 87, 29))
        self.pushButton_29.setObjectName("pushButton_29")
        self.tableWidget_10 = QtWidgets.QTableWidget(self.TabActivities)
        self.tableWidget_10.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget_10.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(4)
        self.tableWidget_10.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(3, item)
        self.MainTabs.addTab(self.TabActivities, "")
        self.TabAdministration = QtWidgets.QWidget()
        self.TabAdministration.setObjectName("TabAdministration")
        self.label_160 = QtWidgets.QLabel(self.TabAdministration)
        self.label_160.setGeometry(QtCore.QRect(10, 40, 161, 17))
        self.label_160.setObjectName("label_160")
        self.label_161 = QtWidgets.QLabel(self.TabAdministration)
        self.label_161.setGeometry(QtCore.QRect(10, 100, 161, 17))
        self.label_161.setObjectName("label_161")
        self.label_162 = QtWidgets.QLabel(self.TabAdministration)
        self.label_162.setGeometry(QtCore.QRect(10, 70, 171, 17))
        self.label_162.setObjectName("label_162")
        self.label_163 = QtWidgets.QLabel(self.TabAdministration)
        self.label_163.setGeometry(QtCore.QRect(500, 10, 231, 17))
        self.label_163.setObjectName("label_163")
        self.label_164 = QtWidgets.QLabel(self.TabAdministration)
        self.label_164.setGeometry(QtCore.QRect(10, 10, 181, 17))
        self.label_164.setObjectName("label_164")
        self.lineEdit_133 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_133.setGeometry(QtCore.QRect(240, 40, 221, 21))
        self.lineEdit_133.setObjectName("lineEdit_133")
        self.lineEdit_138 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_138.setGeometry(QtCore.QRect(240, 70, 221, 21))
        self.lineEdit_138.setObjectName("lineEdit_138")
        self.lineEdit_139 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_139.setGeometry(QtCore.QRect(240, 10, 221, 21))
        self.lineEdit_139.setObjectName("lineEdit_139")
        self.lineEdit_140 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_140.setGeometry(QtCore.QRect(240, 100, 221, 21))
        self.lineEdit_140.setObjectName("lineEdit_140")
        self.lineEdit_141 = QtWidgets.QLineEdit(self.TabAdministration)
        self.lineEdit_141.setGeometry(QtCore.QRect(760, 10, 221, 21))
        self.lineEdit_141.setObjectName("lineEdit_141")
        self.MainTabs.addTab(self.TabAdministration, "")
        self.TabAttachments = QtWidgets.QWidget()
        self.TabAttachments.setObjectName("TabAttachments")
        self.pushButton_30 = QtWidgets.QPushButton(self.TabAttachments)
        self.pushButton_30.setGeometry(QtCore.QRect(100, 10, 87, 29))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.TabAttachments)
        self.pushButton_31.setGeometry(QtCore.QRect(10, 10, 87, 29))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.TabAttachments)
        self.pushButton_32.setGeometry(QtCore.QRect(190, 10, 87, 29))
        self.pushButton_32.setObjectName("pushButton_32")
        self.tableWidget_11 = QtWidgets.QTableWidget(self.TabAttachments)
        self.tableWidget_11.setGeometry(QtCore.QRect(10, 60, 751, 121))
        self.tableWidget_11.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_11.setObjectName("tableWidget_11")
        self.tableWidget_11.setColumnCount(3)
        self.tableWidget_11.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_11.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_11.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_11.setHorizontalHeaderItem(2, item)
        self.pushButton_33 = QtWidgets.QPushButton(self.TabAttachments)
        self.pushButton_33.setGeometry(QtCore.QRect(280, 10, 87, 29))
        self.pushButton_33.setObjectName("pushButton_33")
        self.MainTabs.addTab(self.TabAttachments, "")
        self.TabRates = QtWidgets.QWidget()
        self.TabRates.setObjectName("TabRates")
        self.tableWidget_12 = QtWidgets.QTableWidget(self.TabRates)
        self.tableWidget_12.setGeometry(QtCore.QRect(10, 50, 751, 121))
        self.tableWidget_12.setMaximumSize(QtCore.QSize(751, 121))
        self.tableWidget_12.setObjectName("tableWidget_12")
        self.tableWidget_12.setColumnCount(8)
        self.tableWidget_12.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_12.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_12.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_12.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(7, item)
        self.dateEdit = QtWidgets.QDateEdit(self.TabRates)
        self.dateEdit.setGeometry(QtCore.QRect(60, 10, 119, 28))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.TabRates)
        self.dateEdit_2.setGeometry(QtCore.QRect(240, 10, 121, 28))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_165 = QtWidgets.QLabel(self.TabRates)
        self.label_165.setGeometry(QtCore.QRect(10, 20, 41, 17))
        self.label_165.setObjectName("label_165")
        self.label_166 = QtWidgets.QLabel(self.TabRates)
        self.label_166.setGeometry(QtCore.QRect(190, 20, 41, 17))
        self.label_166.setObjectName("label_166")
        self.pushButton_34 = QtWidgets.QPushButton(self.TabRates)
        self.pushButton_34.setGeometry(QtCore.QRect(380, 10, 111, 29))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.TabRates)
        self.pushButton_35.setGeometry(QtCore.QRect(506, 10, 131, 29))
        self.pushButton_35.setObjectName("pushButton_35")
        self.MainTabs.addTab(self.TabRates, "")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(70, 710, 721, 81))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 650, 781, 41))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 779, 39))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 10, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 10, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(830, 660, 107, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(950, 660, 107, 30))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(830, 710, 107, 30))
        self.pushButton_11.setObjectName("pushButton_11")
        ClientDetails.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ClientDetails)
        self.statusbar.setObjectName("statusbar")
        ClientDetails.setStatusBar(self.statusbar)
        #self.pushButton.clicked.connect(self.InsertData)
        self.pushButton_12.clicked.connect(self.openWindow1)

        self.retranslateUi(ClientDetails)
        self.MainTabs.setCurrentIndex(0)
        self.Address.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ClientDetails)


    def openWindow1(self):
        self.window = QtWidgets.QMainWindow()
        self.ui1 = Ui_ClientContactDetails()
        self.ui1.setupUi(self.window)
        self.window.show()


    def retranslateUi(self, ClientDetails):
        _translate = QtCore.QCoreApplication.translate
        ClientDetails.setWindowTitle(_translate("ClientDetails", "Client Details Update"))
        self.label_1.setText(_translate("ClientDetails", "Company Name:"))
        self.label_2.setText(_translate("ClientDetails", "VAT Registraion Number:"))
        self.label_3.setText(_translate("ClientDetails", "Payroll Code:"))
        self.label_4.setText(_translate("ClientDetails", "Integration Code:"))
        self.label_14.setText(_translate("ClientDetails", "Telephone Fax:"))
        self.label_18.setText(_translate("ClientDetails", "Category:"))
        self.label_17.setText(_translate("ClientDetails", "Invoice Template:"))
        self.label_13.setText(_translate("ClientDetails", "Telephone Work:"))
        self.label_12.setText(_translate("ClientDetails", "Folder (Status):"))
        self.label_16.setText(_translate("ClientDetails", "Email Address:"))
        self.label_23.setText(_translate("ClientDetails", "Street Nr:"))
        self.label_27.setText(_translate("ClientDetails", "Postal Code:"))
        self.lineEdit_28.setText(_translate("ClientDetails", "South Africa"))
        self.label_26.setText(_translate("ClientDetails", "City/Town:"))
        self.label_25.setText(_translate("ClientDetails", "Suburb/District:"))
        self.label_22.setText(_translate("ClientDetails", "Complex:"))
        self.label_21.setText(_translate("ClientDetails", "Unit Nr:"))
        self.label_24.setText(_translate("ClientDetails", "Street Name/Farm:"))
        self.label_28.setText(_translate("ClientDetails", "Country/Region:"))
        self.Address.setTabText(self.Address.indexOf(self.Phyical), _translate("ClientDetails", "Phyical"))
        self.label_29.setText(_translate("ClientDetails", "Suburb/District:"))
        self.label_30.setText(_translate("ClientDetails", "City/Town:"))
        self.label_31.setText(_translate("ClientDetails", "Country/Region:"))
        self.lineEdit_29.setText(_translate("ClientDetails", "South Africa"))
        self.label_32.setText(_translate("ClientDetails", "Unit Nr:"))
        self.label_33.setText(_translate("ClientDetails", "Complex:"))
        self.label_34.setText(_translate("ClientDetails", "Street Nr:"))
        self.label_35.setText(_translate("ClientDetails", "Postal Code:"))
        self.label_36.setText(_translate("ClientDetails", "Street Name/Farm:"))
        self.Address.setTabText(self.Address.indexOf(self.Postal), _translate("ClientDetails", "Postal"))
        self.label_37.setText(_translate("ClientDetails", "Suburb/District:"))
        self.label_38.setText(_translate("ClientDetails", "City/Town:"))
        self.label_39.setText(_translate("ClientDetails", "Country/Region:"))
        self.lineEdit_37.setText(_translate("ClientDetails", "South Africa"))
        self.label_40.setText(_translate("ClientDetails", "Unit Nr:"))
        self.label_41.setText(_translate("ClientDetails", "Complex:"))
        self.label_42.setText(_translate("ClientDetails", "Street Nr:"))
        self.lineEdit_38.setText(_translate("ClientDetails", "Strand"))
        self.lineEdit_40.setText(_translate("ClientDetails", "Medx"))
        self.label_43.setText(_translate("ClientDetails", "Postal Code:"))
        self.lineEdit_41.setText(_translate("ClientDetails", "7140"))
        self.lineEdit_42.setText(_translate("ClientDetails", "Main Road"))
        self.lineEdit_43.setText(_translate("ClientDetails", "Cape Town"))
        self.lineEdit_44.setText(_translate("ClientDetails", "36"))
        self.label_44.setText(_translate("ClientDetails", "Street Name/Farm:"))
        self.Address.setTabText(self.Address.indexOf(self.Work), _translate("ClientDetails", "Work"))
        self.label_8.setText(_translate("ClientDetails", "Financial Account Number:"))
        self.label_5.setText(_translate("ClientDetails", "Paying Hours:"))
        self.label_10.setText(_translate("ClientDetails", "Is VAT Payable:"))
        self.label_6.setText(_translate("ClientDetails", "Days Between Payments:"))
        self.label_9.setText(_translate("ClientDetails", "Sales Ledger:"))
        self.label_11.setText(_translate("ClientDetails", "Split Invoice By Department:"))
        self.label_57.setText(_translate("ClientDetails", "Allow Zero Values On Timesheets:"))
        self.label_19.setText(_translate("ClientDetails", "Is Paying Leave:"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab), _translate("ClientDetails", "General"))
        self.pushButton_13.setText(_translate("ClientDetails", "Delete"))
        self.pushButton_12.setText(_translate("ClientDetails", "Add"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "Code"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("ClientDetails", "Description        "))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab_2), _translate("ClientDetails", "Contacts"))
        self.pushButton_7.setText(_translate("ClientDetails", "Add"))
        self.pushButton_8.setText(_translate("ClientDetails", "Delete"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "Code"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ClientDetails", "Description        "))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tabDepartments), _translate("ClientDetails", "Departments"))
        self.pushButton_14.setText(_translate("ClientDetails", "Update"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "CandidateID"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("ClientDetails", "YourID"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("ClientDetails", "SANCReceipt"))
        self.pushButton_15.setText(_translate("ClientDetails", "Add"))
        self.pushButton_16.setText(_translate("ClientDetails", "Delete"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tabUnpreferdCandidates), _translate("ClientDetails", "Unprefered Candidates"))
        self.pushButton_17.setText(_translate("ClientDetails", "Delete"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "Company"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("ClientDetails", "Policy Number"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("ClientDetails", "Expiry Date"))
        self.pushButton_18.setText(_translate("ClientDetails", "Add"))
        self.pushButton_19.setText(_translate("ClientDetails", "Update"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabLinkedUsers), _translate("ClientDetails", "Linked Users"))
        self.pushButton_20.setText(_translate("ClientDetails", "Add"))
        self.pushButton_21.setText(_translate("ClientDetails", "Update"))
        self.pushButton_22.setText(_translate("ClientDetails", "Delete"))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "Description"))
        item = self.tableWidget_8.horizontalHeaderItem(1)
        item.setText(_translate("ClientDetails", "Reference Number"))
        item = self.tableWidget_8.horizontalHeaderItem(2)
        item.setText(_translate("ClientDetails", "Expiry Date"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabUserDefinedFields), _translate("ClientDetails", "User-Defined Fields"))
        self.pushButton_23.setText(_translate("ClientDetails", "Add"))
        self.pushButton_24.setText(_translate("ClientDetails", "Update"))
        item = self.tableWidget_9.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "Preferred"))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("ClientDetails", "Client"))
        item = self.tableWidget_9.horizontalHeaderItem(2)
        item.setText(_translate("ClientDetails", "Candidate Integration Code"))
        self.pushButton_25.setText(_translate("ClientDetails", "Delete"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabLinkedClients), _translate("ClientDetails", "Linked Clients"))
        self.label_149.setText(_translate("ClientDetails", "Extra Qualifications"))
        self.label_150.setText(_translate("ClientDetails", "Extra Qualifications"))
        self.label_151.setText(_translate("ClientDetails", "Previous Work Places"))
        self.label_152.setText(_translate("ClientDetails", "Old Contract"))
        self.label_153.setText(_translate("ClientDetails", "Extra Qualifications"))
        self.label_154.setText(_translate("ClientDetails", "Dislikes"))
        self.label_155.setText(_translate("ClientDetails", "Qualifications"))
        self.pushButton_26.setText(_translate("ClientDetails", "New Field..."))
        self.label_156.setText(_translate("ClientDetails", "Proof of Hepatitis B Injection October 2014"))
        self.label_157.setText(_translate("ClientDetails", "Criminal Check"))
        self.label_158.setText(_translate("ClientDetails", "Reference Check"))
        self.label_159.setText(_translate("ClientDetails", "New Med X Contract October 2014"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabUserDefinedFields1), _translate("ClientDetails", "User-Defined Fields"))
        self.pushButton_27.setText(_translate("ClientDetails", "Update"))
        self.pushButton_28.setText(_translate("ClientDetails", "Add"))
        self.pushButton_29.setText(_translate("ClientDetails", "Delete"))
        item = self.tableWidget_10.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "Occurred At"))
        item = self.tableWidget_10.horizontalHeaderItem(1)
        item.setText(_translate("ClientDetails", "Activity Type"))
        item = self.tableWidget_10.horizontalHeaderItem(2)
        item.setText(_translate("ClientDetails", "User"))
        item = self.tableWidget_10.horizontalHeaderItem(3)
        item.setText(_translate("ClientDetails", "Note"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabActivities), _translate("ClientDetails", "Activities"))
        self.label_160.setText(_translate("ClientDetails", "Created On:"))
        self.label_161.setText(_translate("ClientDetails", "Last Updated On:"))
        self.label_162.setText(_translate("ClientDetails", "Last Updated By:"))
        self.label_163.setText(_translate("ClientDetails", "Last Sanc Warning SMS Sent:"))
        self.label_164.setText(_translate("ClientDetails", "Created By:"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabAdministration), _translate("ClientDetails", "Administration"))
        self.pushButton_30.setText(_translate("ClientDetails", "Update"))
        self.pushButton_31.setText(_translate("ClientDetails", "Add"))
        self.pushButton_32.setText(_translate("ClientDetails", "Delete"))
        item = self.tableWidget_11.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "FileName"))
        item = self.tableWidget_11.horizontalHeaderItem(1)
        item.setText(_translate("ClientDetails", "Descrition"))
        item = self.tableWidget_11.horizontalHeaderItem(2)
        item.setText(_translate("ClientDetails", "NodifiedDate"))
        self.pushButton_33.setText(_translate("ClientDetails", "Open"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabAttachments), _translate("ClientDetails", "Attachments"))
        item = self.tableWidget_12.horizontalHeaderItem(0)
        item.setText(_translate("ClientDetails", "DatePaid"))
        item = self.tableWidget_12.horizontalHeaderItem(1)
        item.setText(_translate("ClientDetails", "PeriodEndDate"))
        item = self.tableWidget_12.horizontalHeaderItem(2)
        item.setText(_translate("ClientDetails", "NodifiedDate"))
        item = self.tableWidget_12.horizontalHeaderItem(3)
        item.setText(_translate("ClientDetails", "GrossEarnings"))
        item = self.tableWidget_12.horizontalHeaderItem(4)
        item.setText(_translate("ClientDetails", "Paye"))
        item = self.tableWidget_12.horizontalHeaderItem(5)
        item.setText(_translate("ClientDetails", "Uif"))
        item = self.tableWidget_12.horizontalHeaderItem(6)
        item.setText(_translate("ClientDetails", "Loans"))
        item = self.tableWidget_12.horizontalHeaderItem(7)
        item.setText(_translate("ClientDetails", "Other"))
        self.label_165.setText(_translate("ClientDetails", "From:"))
        self.label_166.setText(_translate("ClientDetails", "To:"))
        self.pushButton_34.setText(_translate("ClientDetails", "Apply Filter"))
        self.pushButton_35.setText(_translate("ClientDetails", "Clear Filter"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.TabRates), _translate("ClientDetails", "Rates"))
        self.pushButton.setText(_translate("ClientDetails", "Add"))
        self.pushButton_2.setText(_translate("ClientDetails", "Update"))
        self.pushButton_3.setText(_translate("ClientDetails", "Delete"))
        self.pushButton_9.setText(_translate("ClientDetails", "Theme1"))
        self.pushButton_10.setText(_translate("ClientDetails", "Theme2"))
        self.pushButton_11.setText(_translate("ClientDetails", "Theme3"))


    def InsertData(self):
        con = pymysql.connect(host='129.232.195.18',
                             user='pierreb',
                             password='Springboks2017',                             
                             db='medx',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
        with con:
                cur = con.cursor()
                cur.execute("INSERT INTO client2(CompanyName, VATRegistrationNumber, PayrollCode)"
                            "VALUES('%s', '%s', '%s')" %(''.join(self.lineEdit_1.text()),
                                                                                    ''.join(self.lineEdit_2.text()),
                                                                                    ''.join(self.lineEdit_3.text())))

        candidate_id = self.lineEdit.text()
        self.db = pymysql.connect(host='129.232.195.18', port=3306, user='pierreb', password='Springboks2017', db='medx', use_unicode=True,
                               charset='utf8')
        self.cur = self.db.cursor()
              
        sql = ''' SELECT * FROM client2 WHERE ClientID = %s '''
        self.cur.execute(sql , [(client_id)])
        data = self.cur.fetchone()
        #print(data)
        
        self.lineEdit_1.setText(data[8])
        self.lineEdit_2.setText(data[10])
        self.lineEdit_3.setText(data[12])




        print("Client Enrolled Successfully")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClientDetails = QtWidgets.QMainWindow()
    ui = Ui_ClientDetailsUpdate()
    ui.setupUi(ClientDetails)
    ClientDetails.show()
    sys.exit(app.exec_())
