#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon November  12 08:04 2019

@author: pierreb
"""
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication, QVBoxLayout, QPushButton, \
    QTableWidget, QTableWidgetItem, QMessageBox, QHBoxLayout, QLineEdit, QLabel, QGridLayout, QHeaderView
import pymysql
import sys 

class Ui_RateTemplateDetails(object):
    def setupUi(self, RateTemplateDetails):
        RateTemplateDetails.setObjectName("RateTemplateDetails")
        RateTemplateDetails.resize(1053, 777)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("badfavicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RateTemplateDetails.setWindowIcon(icon)
        self.pushButton_6 = QtWidgets.QPushButton(RateTemplateDetails)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 740, 107, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(RateTemplateDetails)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 740, 107, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(RateTemplateDetails)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 0, 1051, 30))
        self.lineEdit_2.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(RateTemplateDetails)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 141, 18))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(RateTemplateDetails)
        self.lineEdit.setGeometry(QtCore.QRect(300, 90, 441, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(RateTemplateDetails)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 331, 18))
        self.label_5.setObjectName("label_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(RateTemplateDetails)
        self.lineEdit_7.setGeometry(QtCore.QRect(190, 50, 551, 30))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_6 = QtWidgets.QLabel(RateTemplateDetails)
        self.label_6.setGeometry(QtCore.QRect(750, 60, 161, 18))
        self.label_6.setObjectName("label_6")
        self.lineEdit_8 = QtWidgets.QLineEdit(RateTemplateDetails)
        self.lineEdit_8.setGeometry(QtCore.QRect(910, 50, 141, 30))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.checkBox = QtWidgets.QCheckBox(RateTemplateDetails)
        self.checkBox.setGeometry(QtCore.QRect(750, 80, 251, 29))
        self.checkBox.setObjectName("checkBox")
        self.tabWidget = QtWidgets.QTabWidget(RateTemplateDetails)
        self.tabWidget.setGeometry(QtCore.QRect(10, 120, 1031, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.Normal_Day = QtWidgets.QWidget()
        self.Normal_Day.setObjectName("Normal_Day")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.Normal_Day)
        self.tableWidget_3.setGeometry(QtCore.QRect(-10, 0, 1041, 581))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_3.verticalHeader().setCascadingSectionResizes(True)
        self.tabWidget.addTab(self.Normal_Day, "")
        self.Normal_Night = QtWidgets.QWidget()
        self.Normal_Night.setObjectName("Normal_Night")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.Normal_Night)
        self.tableWidget_2.setGeometry(QtCore.QRect(-10, 0, 1041, 581))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(True)
        self.tabWidget.addTab(self.Normal_Night, "")
        self.Saturday_Day = QtWidgets.QWidget()
        self.Saturday_Day.setObjectName("Saturday_Day")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.Saturday_Day)
        self.tableWidget_4.setGeometry(QtCore.QRect(-10, 0, 1041, 581))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        self.tableWidget_4.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_4.verticalHeader().setCascadingSectionResizes(True)
        self.tabWidget.addTab(self.Saturday_Day, "")
        self.Saturday_Night = QtWidgets.QWidget()
        self.Saturday_Night.setObjectName("Saturday_Night")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.Saturday_Night)
        self.tableWidget_5.setGeometry(QtCore.QRect(-10, 0, 1041, 581))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(4)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        self.tableWidget_5.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_5.verticalHeader().setCascadingSectionResizes(True)
        self.tabWidget.addTab(self.Saturday_Night, "")
        self.Sunday_Day = QtWidgets.QWidget()
        self.Sunday_Day.setObjectName("Sunday_Day")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.Sunday_Day)
        self.tableWidget_6.setGeometry(QtCore.QRect(-10, 0, 1041, 591))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(4)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        self.tableWidget_6.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_6.verticalHeader().setCascadingSectionResizes(True)
        self.tabWidget.addTab(self.Sunday_Day, "")
        self.Sunday_Night = QtWidgets.QWidget()
        self.Sunday_Night.setObjectName("Sunday_Night")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.Sunday_Night)
        self.tableWidget_7.setGeometry(QtCore.QRect(-10, 0, 1041, 581))
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(4)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, item)
        self.tableWidget_7.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_7.verticalHeader().setCascadingSectionResizes(True)
        self.tabWidget.addTab(self.Sunday_Night, "")
        self.Public_Holiday_Day = QtWidgets.QWidget()
        self.Public_Holiday_Day.setObjectName("Public_Holiday_Day")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.Public_Holiday_Day)
        self.tableWidget_8.setGeometry(QtCore.QRect(-10, 0, 1041, 581))
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(4)
        self.tableWidget_8.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(3, item)
        self.tableWidget_8.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_8.verticalHeader().setCascadingSectionResizes(True)
        self.tabWidget.addTab(self.Public_Holiday_Day, "")
        self.Public_Holiday_Night = QtWidgets.QWidget()
        self.Public_Holiday_Night.setObjectName("Public_Holiday_Night")
        self.tableWidget_9 = QtWidgets.QTableWidget(self.Public_Holiday_Night)
        self.tableWidget_9.setGeometry(QtCore.QRect(-10, 0, 1041, 581))
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(4)
        self.tableWidget_9.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(3, item)
        self.tableWidget_9.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_9.verticalHeader().setCascadingSectionResizes(True)
        self.tabWidget.addTab(self.Public_Holiday_Night, "")

        self.retranslateUi(RateTemplateDetails)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RateTemplateDetails)

    def retranslateUi(self, RateTemplateDetails):
        _translate = QtCore.QCoreApplication.translate
        RateTemplateDetails.setWindowTitle(_translate("RateTemplateDetails", "ProTemp"))
        self.pushButton_6.setText(_translate("RateTemplateDetails", "Cancel"))
        self.pushButton_5.setText(_translate("RateTemplateDetails", "Ok"))
        self.lineEdit_2.setText(_translate("RateTemplateDetails", "Rate Template Details"))
        self.label_4.setText(_translate("RateTemplateDetails", "Description:"))
        self.label_5.setText(_translate("RateTemplateDetails", "Only show Qualifications contaning:"))
        self.label_6.setText(_translate("RateTemplateDetails", "Default Commission:"))
        self.checkBox.setText(_translate("RateTemplateDetails", "Show only values > R0.00"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("RateTemplateDetails", "Qualification"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("RateTemplateDetails", "Client Rate"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("RateTemplateDetails", "Commision Percentage"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("RateTemplateDetails", "Candidate Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Normal_Day), _translate("RateTemplateDetails", "Normal Day"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("RateTemplateDetails", "Qualification"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("RateTemplateDetails", "Client Rate"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("RateTemplateDetails", "Commision Percentage"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("RateTemplateDetails", "Candidate Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Normal_Night), _translate("RateTemplateDetails", "Normal Night"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("RateTemplateDetails", "Qualification"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("RateTemplateDetails", "Client Rate"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("RateTemplateDetails", "Commision Percentage"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("RateTemplateDetails", "Candidate Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Saturday_Day), _translate("RateTemplateDetails", "Saturday Day"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("RateTemplateDetails", "Qualification"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("RateTemplateDetails", "Client Rate"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("RateTemplateDetails", "Commision Percentage"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("RateTemplateDetails", "Candidate Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Saturday_Night), _translate("RateTemplateDetails", "Saturday Night"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("RateTemplateDetails", "Qualification"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("RateTemplateDetails", "Client Rate"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("RateTemplateDetails", "Commision Percentage"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("RateTemplateDetails", "Candidate Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Sunday_Day), _translate("RateTemplateDetails", "Sunday Day"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("RateTemplateDetails", "Qualification"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("RateTemplateDetails", "Client Rate"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("RateTemplateDetails", "Commision Percentage"))
        item = self.tableWidget_7.horizontalHeaderItem(3)
        item.setText(_translate("RateTemplateDetails", "Candidate Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Sunday_Night), _translate("RateTemplateDetails", "Sunday Night"))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("RateTemplateDetails", "Qualification"))
        item = self.tableWidget_8.horizontalHeaderItem(1)
        item.setText(_translate("RateTemplateDetails", "Client Rate"))
        item = self.tableWidget_8.horizontalHeaderItem(2)
        item.setText(_translate("RateTemplateDetails", "Commision Percentage"))
        item = self.tableWidget_8.horizontalHeaderItem(3)
        item.setText(_translate("RateTemplateDetails", "Candidate Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Public_Holiday_Day), _translate("RateTemplateDetails", "Public Holiday Day"))
        item = self.tableWidget_9.horizontalHeaderItem(0)
        item.setText(_translate("RateTemplateDetails", "Qualification"))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("RateTemplateDetails", "Client Rate"))
        item = self.tableWidget_9.horizontalHeaderItem(2)
        item.setText(_translate("RateTemplateDetails", "Commision Percentage"))
        item = self.tableWidget_9.horizontalHeaderItem(3)
        item.setText(_translate("RateTemplateDetails", "Candidate Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Public_Holiday_Night), _translate("RateTemplateDetails", "Public Holiday Night"))


        self.Rate_Details_Normal_Day()
        self.Rate_Details_Normal_Night()
        self.Rate_Details_Saturday_Day()


    def Rate_Details_Normal_Day(self):
        self.db = pymysql.connect(host='129.232.195.18', port=3306, user='pierreb', password='Springboks2017', db='medx', use_unicode=True,
                               charset='utf8')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT id, Rate, CommissionPercentage, Rate FROM RateTemplateDetail''')
        data = self.cur.fetchall()

        self.tableWidget_3.insertRow(0)

        for row , form in enumerate(data):
            for column , item in enumerate(form):
                self.tableWidget_3.setItem(row , column , QTableWidgetItem(str(item)))
                
                column += 1

            row_position = self.tableWidget_3.rowCount()
            self.tableWidget_3.insertRow(row_position)


    def Rate_Details_Normal_Night(self):
        self.db = pymysql.connect(host='129.232.195.18', port=3306, user='pierreb', password='Springboks2017', db='medx', use_unicode=True,
                               charset='utf8')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT id, Rate, CommissionPercentage, Rate FROM RateTemplateDetail''')
        data = self.cur.fetchall()

        self.tableWidget_2.insertRow(0)

        for row , form in enumerate(data):
            for column , item in enumerate(form):
                self.tableWidget_2.setItem(row , column , QTableWidgetItem(str(item)))
                
                column += 1

            row_position = self.tableWidget_2.rowCount()
            self.tableWidget_2.insertRow(row_position)


    def Rate_Details_Saturday_Day(self):
        self.db = pymysql.connect(host='129.232.195.18', port=3306, user='pierreb', password='Springboks2017', db='medx', use_unicode=True,
                               charset='utf8')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT id, Rate, CommissionPercentage, Rate FROM RateTemplateDetail''')
        data = self.cur.fetchall()

        self.tableWidget_4.insertRow(0)

        for row , form in enumerate(data):
            for column , item in enumerate(form):
                self.tableWidget_4.setItem(row , column , QTableWidgetItem(str(item)))
                
                column += 1

            row_position = self.tableWidget_4.rowCount()
            self.tableWidget_4.insertRow(row_position)


    def Rate_Details_Saturday_Night(self):
        self.db = pymysql.connect(host='129.232.195.18', port=3306, user='pierreb', password='Springboks2017', db='medx', use_unicode=True,
                               charset='utf8')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT id, Rate, CommissionPercentage, Rate FROM RateTemplateDetail''')
        data = self.cur.fetchall()

        self.tableWidget_2.insertRow(0)

        for row , form in enumerate(data):
            for column , item in enumerate(form):
                self.tableWidget_2.setItem(row , column , QTableWidgetItem(str(item)))
                
                column += 1

            row_position = self.tableWidget_2.rowCount()
            self.tableWidget_2.insertRow(row_position)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RateTemplateDetails = QtWidgets.QWidget()
    ui = Ui_RateTemplateDetails()
    ui.setupUi(RateTemplateDetails)
    RateTemplateDetails.show()
    sys.exit(app.exec_())

