#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu November 21 10:41 2019

Last Updated Wed February 19 12:23 2020

@author: pierreb
"""

from PyQt5 import QtCore, QtGui, QtWidgets, uic
import pymysql
import time
import sys
from PyQt5.uic import loadUiType
from clickatell.http import Http
from PyQt5.QtWidgets import qApp
from PyQt5.QtCore import Qt, QModelIndex
from PyQt5.QtWidgets import QWidget, QApplication, QVBoxLayout, QPushButton, \
    QTableWidget, QTableWidgetItem, QMessageBox, QHBoxLayout, QLineEdit, QLabel, QGridLayout, QCheckBox, QHeaderView
from Qualification_add import Ui_Form


class Ui_TimesheetDetails(object):
    def setupUi(self, TimesheetDetails):
        TimesheetDetails.setObjectName("TimesheetDetails")
        TimesheetDetails.resize(1053, 777)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("badfavicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TimesheetDetails.setWindowIcon(icon)
        self.pushButton_6 = QtWidgets.QPushButton(TimesheetDetails)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 740, 107, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(TimesheetDetails)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 740, 107, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 0, 1051, 30))
        self.lineEdit_2.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox_2 = QtWidgets.QComboBox(TimesheetDetails)
        self.comboBox_2.setGeometry(QtCore.QRect(190, 40, 771, 28))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_4 = QtWidgets.QLabel(TimesheetDetails)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 141, 18))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(TimesheetDetails)
        self.label_8.setGeometry(QtCore.QRect(510, 740, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(TimesheetDetails)
        self.label_9.setGeometry(QtCore.QRect(640, 740, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("background-color: rgb(188, 255, 169);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(TimesheetDetails)
        self.label_6.setGeometry(QtCore.QRect(800, 750, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(TimesheetDetails)
        self.label_10.setGeometry(QtCore.QRect(760, 740, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("background-color: rgb(171, 171, 171);\n"
"border-color: rgb(0, 0, 0);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(TimesheetDetails)
        self.label_7.setGeometry(QtCore.QRect(550, 750, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(TimesheetDetails)
        self.label_11.setGeometry(QtCore.QRect(680, 750, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.tableWidget = QtWidgets.QTableWidget(TimesheetDetails)
        self.tableWidget.setGeometry(QtCore.QRect(5, 210, 1041, 351))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.lineEdit = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit.setGeometry(QtCore.QRect(190, 80, 811, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(TimesheetDetails)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 151, 18))
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(TimesheetDetails)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 121, 18))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(TimesheetDetails)
        self.label_13.setGeometry(QtCore.QRect(20, 170, 111, 18))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(TimesheetDetails)
        self.label_14.setGeometry(QtCore.QRect(500, 170, 151, 18))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(TimesheetDetails)
        self.label_15.setGeometry(QtCore.QRect(500, 130, 141, 18))
        self.label_15.setObjectName("label_15")
        self.lineEdit_3 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 120, 281, 30))
        self.lineEdit_3.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 160, 281, 30))
        self.lineEdit_4.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_5.setGeometry(QtCore.QRect(660, 120, 281, 30))
        self.lineEdit_5.setStyleSheet("background-color: rgb(239, 235, 231);\n"
"border-right-color: rgb(239, 235, 231);\n"
"gridline-color: rgb(239, 235, 231);\n"
"border-top-color: rgb(239, 235, 231);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_6.setGeometry(QtCore.QRect(660, 160, 281, 30))
        self.lineEdit_6.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_7 = QtWidgets.QPushButton(TimesheetDetails)
        self.pushButton_7.setGeometry(QtCore.QRect(970, 40, 31, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 690, 841, 30))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_16 = QtWidgets.QLabel(TimesheetDetails)
        self.label_16.setGeometry(QtCore.QRect(20, 580, 161, 18))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(TimesheetDetails)
        self.label_17.setGeometry(QtCore.QRect(20, 700, 191, 18))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(TimesheetDetails)
        self.label_18.setGeometry(QtCore.QRect(20, 620, 111, 18))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(TimesheetDetails)
        self.label_19.setGeometry(QtCore.QRect(20, 650, 81, 18))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(TimesheetDetails)
        self.label_20.setGeometry(QtCore.QRect(500, 650, 131, 18))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(TimesheetDetails)
        self.label_21.setGeometry(QtCore.QRect(500, 580, 161, 18))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(TimesheetDetails)
        self.label_22.setGeometry(QtCore.QRect(500, 620, 111, 18))
        self.label_22.setObjectName("label_22")
        self.lineEdit_8 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_8.setGeometry(QtCore.QRect(190, 570, 281, 30))
        self.lineEdit_8.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_9.setGeometry(QtCore.QRect(190, 610, 281, 30))
        self.lineEdit_9.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_10.setGeometry(QtCore.QRect(660, 570, 281, 30))
        self.lineEdit_10.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_11.setGeometry(QtCore.QRect(660, 610, 281, 30))
        self.lineEdit_11.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_12.setGeometry(QtCore.QRect(660, 650, 281, 30))
        self.lineEdit_12.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_13.setGeometry(QtCore.QRect(190, 650, 281, 30))
        self.lineEdit_13.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_23 = QtWidgets.QLabel(TimesheetDetails)
        self.label_23.setGeometry(QtCore.QRect(950, 750, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(TimesheetDetails)
        self.label_24.setGeometry(QtCore.QRect(910, 740, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setAutoFillBackground(False)
        self.label_24.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 0, 0, 255), stop:0.479904 rgba(255, 0, 0, 255), stop:0.522685 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.pushButton_8 = QtWidgets.QPushButton(TimesheetDetails)
        self.pushButton_8.setGeometry(QtCore.QRect(970, 570, 71, 30))
        self.pushButton_8.setStyleSheet("font: 11pt \"Abyssinica SIL\";\n"
"text-decoration: underline;\n"
"color: rgb(0, 0, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.comboBox = QtWidgets.QComboBox(TimesheetDetails)
        self.comboBox.setGeometry(QtCore.QRect(180, 240, 71, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(TimesheetDetails)
        QtCore.QMetaObject.connectSlotsByName(TimesheetDetails)

    def retranslateUi(self, TimesheetDetails):
        _translate = QtCore.QCoreApplication.translate
        TimesheetDetails.setWindowTitle(_translate("TimesheetDetails", "ProTemp"))
        self.pushButton_6.setText(_translate("TimesheetDetails", "Cancel"))
        self.pushButton_5.setText(_translate("TimesheetDetails", "Ok"))
        self.lineEdit_2.setText(_translate("TimesheetDetails", "Timesheet Details"))
        self.label_4.setText(_translate("TimesheetDetails", "Client:"))
        self.label_6.setText(_translate("TimesheetDetails", "Under Paid"))
        self.label_7.setText(_translate("TimesheetDetails", "Processed"))
        self.label_11.setText(_translate("TimesheetDetails", "Over Paid"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("TimesheetDetails", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TimesheetDetails", "Sort"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TimesheetDetails", "Date"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TimesheetDetails", "ID"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TimesheetDetails", "Candidate"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TimesheetDetails", "Dept."))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TimesheetDetails", "Qual"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TimesheetDetails", "Start"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("TimesheetDetails", "End"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("TimesheetDetails", "Hours"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("TimesheetDetails", "Rate"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("TimesheetDetails", "123"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("TimesheetDetails", "Reference Number:"))
        self.label_12.setText(_translate("TimesheetDetails", "Created By:"))
        self.label_13.setText(_translate("TimesheetDetails", "Created On:"))
        self.label_14.setText(_translate("TimesheetDetails", "Last Updated On:"))
        self.label_15.setText(_translate("TimesheetDetails", "Last Updated By:"))
        self.pushButton_7.setText(_translate("TimesheetDetails", "Ok"))
        self.label_16.setText(_translate("TimesheetDetails", "Candidate Category:"))
        self.label_17.setText(_translate("TimesheetDetails", "Note:"))
        self.label_18.setText(_translate("TimesheetDetails", "Qualification:"))
        self.label_19.setText(_translate("TimesheetDetails", "SANC Ref:"))
        self.label_20.setText(_translate("TimesheetDetails", "Timesheet Total:"))
        self.label_21.setText(_translate("TimesheetDetails", "Department:"))
        self.label_22.setText(_translate("TimesheetDetails", "Shift:"))
        self.label_23.setText(_translate("TimesheetDetails", "Open"))
        self.pushButton_8.setText(_translate("TimesheetDetails", "Rates"))
        self.comboBox.setItemText(0, _translate("TimesheetDetails", "1"))
        self.comboBox.setItemText(1, _translate("TimesheetDetails", "2"))
        self.comboBox.setItemText(2, _translate("TimesheetDetails", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TimesheetDetails = QtWidgets.QWidget()
    ui = Ui_TimesheetDetails()
    ui.setupUi(TimesheetDetails)
    TimesheetDetails.show()
    sys.exit(app.exec_())
