# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Timesheet_Details_v108.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimesheetDetails(object):
    def setupUi(self, TimesheetDetails):
        TimesheetDetails.setObjectName("TimesheetDetails")
        TimesheetDetails.resize(1053, 690)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("badfavicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TimesheetDetails.setWindowIcon(icon)
        self.pushButton_6 = QtWidgets.QPushButton(TimesheetDetails)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 630, 107, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(TimesheetDetails)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 630, 107, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 0, 1051, 30))
        self.lineEdit_2.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox_2 = QtWidgets.QComboBox(TimesheetDetails)
        self.comboBox_2.setGeometry(QtCore.QRect(190, 40, 771, 28))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_4 = QtWidgets.QLabel(TimesheetDetails)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 41, 18))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(TimesheetDetails)
        self.label_8.setGeometry(QtCore.QRect(510, 630, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(TimesheetDetails)
        self.label_9.setGeometry(QtCore.QRect(640, 630, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("background-color: rgb(188, 255, 169);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(TimesheetDetails)
        self.label_6.setGeometry(QtCore.QRect(800, 640, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(TimesheetDetails)
        self.label_10.setGeometry(QtCore.QRect(760, 630, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("background-color: rgb(171, 171, 171);\n"
"border-color: rgb(0, 0, 0);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(TimesheetDetails)
        self.label_7.setGeometry(QtCore.QRect(550, 640, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(TimesheetDetails)
        self.label_11.setGeometry(QtCore.QRect(680, 640, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.lineEdit = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit.setGeometry(QtCore.QRect(190, 80, 811, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(TimesheetDetails)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 151, 18))
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(TimesheetDetails)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 121, 18))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(TimesheetDetails)
        self.label_13.setGeometry(QtCore.QRect(20, 170, 111, 18))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(TimesheetDetails)
        self.label_14.setGeometry(QtCore.QRect(500, 170, 151, 18))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(TimesheetDetails)
        self.label_15.setGeometry(QtCore.QRect(500, 130, 141, 18))
        self.label_15.setObjectName("label_15")
        self.lineEdit_3 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 120, 281, 30))
        self.lineEdit_3.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 160, 281, 30))
        self.lineEdit_4.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_5.setGeometry(QtCore.QRect(660, 120, 281, 30))
        self.lineEdit_5.setStyleSheet("background-color: rgb(239, 235, 231);\n"
"border-right-color: rgb(239, 235, 231);\n"
"gridline-color: rgb(239, 235, 231);\n"
"border-top-color: rgb(239, 235, 231);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_6.setGeometry(QtCore.QRect(660, 160, 281, 30))
        self.lineEdit_6.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_7 = QtWidgets.QPushButton(TimesheetDetails)
        self.pushButton_7.setGeometry(QtCore.QRect(970, 40, 31, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 580, 841, 30))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_16 = QtWidgets.QLabel(TimesheetDetails)
        self.label_16.setGeometry(QtCore.QRect(20, 470, 161, 18))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(TimesheetDetails)
        self.label_17.setGeometry(QtCore.QRect(20, 590, 191, 18))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(TimesheetDetails)
        self.label_18.setGeometry(QtCore.QRect(20, 510, 111, 18))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(TimesheetDetails)
        self.label_19.setGeometry(QtCore.QRect(20, 540, 81, 18))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(TimesheetDetails)
        self.label_20.setGeometry(QtCore.QRect(500, 540, 131, 18))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(TimesheetDetails)
        self.label_21.setGeometry(QtCore.QRect(500, 470, 161, 18))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(TimesheetDetails)
        self.label_22.setGeometry(QtCore.QRect(500, 510, 111, 18))
        self.label_22.setObjectName("label_22")
        self.lineEdit_8 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_8.setGeometry(QtCore.QRect(190, 460, 281, 30))
        self.lineEdit_8.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_9.setGeometry(QtCore.QRect(190, 500, 281, 30))
        self.lineEdit_9.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_10.setGeometry(QtCore.QRect(660, 460, 281, 30))
        self.lineEdit_10.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_11.setGeometry(QtCore.QRect(660, 500, 281, 30))
        self.lineEdit_11.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_12.setGeometry(QtCore.QRect(660, 540, 281, 30))
        self.lineEdit_12.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_13.setGeometry(QtCore.QRect(190, 540, 281, 30))
        self.lineEdit_13.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_23 = QtWidgets.QLabel(TimesheetDetails)
        self.label_23.setGeometry(QtCore.QRect(950, 640, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(TimesheetDetails)
        self.label_24.setGeometry(QtCore.QRect(910, 630, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setAutoFillBackground(False)
        self.label_24.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 0, 0, 255), stop:0.479904 rgba(255, 0, 0, 255), stop:0.522685 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.pushButton_8 = QtWidgets.QPushButton(TimesheetDetails)
        self.pushButton_8.setGeometry(QtCore.QRect(970, 460, 71, 30))
        self.pushButton_8.setStyleSheet("font: 11pt \"Abyssinica SIL\";\n"
"text-decoration: underline;\n"
"color: rgb(0, 0, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_14 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_14.setGeometry(QtCore.QRect(160, 240, 81, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_16 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_16.setGeometry(QtCore.QRect(320, 240, 81, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_20 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_20.setGeometry(QtCore.QRect(640, 240, 81, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_21.setGeometry(QtCore.QRect(720, 240, 81, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_22.setGeometry(QtCore.QRect(800, 240, 81, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(TimesheetDetails)
        self.lineEdit_23.setGeometry(QtCore.QRect(880, 240, 81, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.dateEdit = QtWidgets.QDateEdit(TimesheetDetails)
        self.dateEdit.setGeometry(QtCore.QRect(240, 240, 81, 20))
        self.dateEdit.setObjectName("dateEdit")
        self.comboBox = QtWidgets.QComboBox(TimesheetDetails)
        self.comboBox.setGeometry(QtCore.QRect(400, 240, 81, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_3 = QtWidgets.QComboBox(TimesheetDetails)
        self.comboBox_3.setGeometry(QtCore.QRect(480, 240, 81, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(TimesheetDetails)
        self.comboBox_4.setGeometry(QtCore.QRect(560, 240, 81, 20))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_25 = QtWidgets.QLabel(TimesheetDetails)
        self.label_25.setGeometry(QtCore.QRect(170, 220, 41, 18))
        self.label_25.setStyleSheet("font: 10pt \"Calibri\";")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(TimesheetDetails)
        self.label_26.setGeometry(QtCore.QRect(250, 220, 41, 18))
        self.label_26.setStyleSheet("font: 10pt \"MS Serif\";")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(TimesheetDetails)
        self.label_27.setGeometry(QtCore.QRect(330, 220, 41, 18))
        self.label_27.setStyleSheet("font: 10pt \"MS Gothic\";")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(TimesheetDetails)
        self.label_28.setGeometry(QtCore.QRect(410, 220, 71, 18))
        self.label_28.setStyleSheet("font: 75 10pt \"Rubik\";")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(TimesheetDetails)
        self.label_29.setGeometry(QtCore.QRect(490, 220, 61, 18))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(TimesheetDetails)
        self.label_30.setGeometry(QtCore.QRect(570, 220, 61, 18))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(TimesheetDetails)
        self.label_31.setGeometry(QtCore.QRect(650, 220, 61, 18))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(TimesheetDetails)
        self.label_32.setGeometry(QtCore.QRect(730, 220, 61, 18))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(TimesheetDetails)
        self.label_33.setGeometry(QtCore.QRect(810, 220, 61, 18))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(TimesheetDetails)
        self.label_34.setGeometry(QtCore.QRect(890, 220, 61, 18))
        self.label_34.setObjectName("label_34")

        self.retranslateUi(TimesheetDetails)
        QtCore.QMetaObject.connectSlotsByName(TimesheetDetails)

    def retranslateUi(self, TimesheetDetails):
        _translate = QtCore.QCoreApplication.translate
        TimesheetDetails.setWindowTitle(_translate("TimesheetDetails", "ProTemp"))
        self.pushButton_6.setText(_translate("TimesheetDetails", "Cancel"))
        self.pushButton_5.setText(_translate("TimesheetDetails", "Ok"))
        self.lineEdit_2.setText(_translate("TimesheetDetails", "Timesheet Details"))
        self.label_4.setText(_translate("TimesheetDetails", "Client:"))
        self.label_6.setText(_translate("TimesheetDetails", "Under Paid"))
        self.label_7.setText(_translate("TimesheetDetails", "Processed"))
        self.label_11.setText(_translate("TimesheetDetails", "Over Paid"))
        self.label_5.setText(_translate("TimesheetDetails", "Reference Number:"))
        self.label_12.setText(_translate("TimesheetDetails", "Created By:"))
        self.label_13.setText(_translate("TimesheetDetails", "Created On:"))
        self.label_14.setText(_translate("TimesheetDetails", "Last Updated On:"))
        self.label_15.setText(_translate("TimesheetDetails", "Last Updated By:"))
        self.pushButton_7.setText(_translate("TimesheetDetails", "Ok"))
        self.label_16.setText(_translate("TimesheetDetails", "Candidate Category:"))
        self.label_17.setText(_translate("TimesheetDetails", "Note:"))
        self.label_18.setText(_translate("TimesheetDetails", "Qualification:"))
        self.label_19.setText(_translate("TimesheetDetails", "SANC Ref:"))
        self.label_20.setText(_translate("TimesheetDetails", "Timesheet Total:"))
        self.label_21.setText(_translate("TimesheetDetails", "Department:"))
        self.label_22.setText(_translate("TimesheetDetails", "Shift:"))
        self.label_23.setText(_translate("TimesheetDetails", "Open"))
        self.pushButton_8.setText(_translate("TimesheetDetails", "Rates"))
        self.label_25.setText(_translate("TimesheetDetails", "<html><head/><body><p><span style=\" font-weight:600;\">Sort</span></p></body></html>"))
        self.label_26.setText(_translate("TimesheetDetails", "<html><head/><body><p><span style=\" font-weight:600;\">Date</span></p></body></html>"))
        self.label_27.setText(_translate("TimesheetDetails", "<html><head/><body><p><span style=\" font-weight:600;\">ID</span></p></body></html>"))
        self.label_28.setText(_translate("TimesheetDetails", "<html><head/><body><p><span style=\" font-weight:600;\">Candidate</span></p></body></html>"))
        self.label_29.setText(_translate("TimesheetDetails", "<html><head/><body><p><span style=\" font-weight:600;\">Dept.</span></p></body></html>"))
        self.label_30.setText(_translate("TimesheetDetails", "<html><head/><body><p><span style=\" font-weight:600;\">Qual</span></p></body></html>"))
        self.label_31.setText(_translate("TimesheetDetails", "<html><head/><body><p><span style=\" font-weight:600;\">Start</span></p></body></html>"))
        self.label_32.setText(_translate("TimesheetDetails", "<html><head/><body><p><span style=\" font-weight:600;\">End</span></p></body></html>"))
        self.label_33.setText(_translate("TimesheetDetails", "<html><head/><body><p><span style=\" font-weight:600;\">Hours</span></p></body></html>"))
        self.label_34.setText(_translate("TimesheetDetails", "<html><head/><body><p><span style=\" font-weight:600;\">Rate</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TimesheetDetails = QtWidgets.QWidget()
    ui = Ui_TimesheetDetails()
    ui.setupUi(TimesheetDetails)
    TimesheetDetails.show()
    sys.exit(app.exec_())
